/**
 * @file word_pool.h
 * @brief 小学英语词库 v14：入门档+PEP 3-6 年级（1148 词，v14 校正释义）
 * 字段：en 英文 / cn 中文释义 / ph 音标(英音) / book 档(0=入门..8=六下)
 */
#ifndef WORD_POOL_H
#define WORD_POOL_H

#include <stdint.h>

typedef struct {
    const char *en;
    const char *cn;
    const char *ph;
    uint8_t book;
} word_entry_t;

#define WORD_POOL_SIZE 1148

static const word_entry_t word_pool[] = {
    {"actor", "演员", "ˈæktə(r)", 0},
    {"ankle", "脚踝", "ˈæŋk(ə)l", 0},
    {"answer", "回答", "ˈɑːnsə(r)", 0},
    {"apron", "围裙", "ˈeɪprən", 0},
    {"baby", "婴儿", "ˈbeɪbi", 0},
    {"backpack", "背包", "ˈbækpæk", 0},
    {"bacon", "培根", "ˈbeɪkən", 0},
    {"bake", "烤", "beɪk", 0},
    {"balloon", "气球", "bəˈluːn", 0},
    {"bank", "银行", "bæŋk", 0},
    {"bat", "球棒，蝙蝠", "bæt", 0},
    {"bee", "蜜蜂", "biː", 0},
    {"beetle", "甲虫", "ˈbiːtl", 0},
    {"bell", "铃", "bel", 0},
    {"below", "在……下面", "bɪˈləʊ", 0},
    {"belt", "腰带", "belt", 0},
    {"biscuit", "饼干", "ˈbɪskɪt", 0},
    {"blanket", "毛毯", "ˈblæŋkɪt", 0},
    {"blood", "血", "blʌd", 0},
    {"bone", "骨头", "bəʊn", 0},
    {"boot", "靴子", "buːt", 0},
    {"bored", "无聊的", "bɔːd", 0},
    {"boss", "老板", "bɒs", 0},
    {"brave", "勇敢的", "breɪv", 0},
    {"brush", "刷子", "brʌʃ", 0},
    {"build", "建造", "bɪld", 0},
    {"butter", "黄油", "ˈbʌtə(r)", 0},
    {"butterfly", "蝴蝶", "ˈbʌtəflaɪ", 0},
    {"button", "纽扣", "ˈbʌt(ə)n", 0},
    {"cabbage", "卷心菜", "ˈkæbɪdʒ", 0},
    {"camel", "骆驼", "ˈkæm(ə)l", 0},
    {"camera", "照相机", "ˈkæm(ə)rə", 0},
    {"candle", "蜡烛", "ˈkænd(ə)l", 0},
    {"careful", "小心的", "ˈkeəf(ə)l", 0},
    {"carpet", "地毯", "ˈkɑːpɪt", 0},
    {"carry", "搬，提", "ˈkæri", 0},
    {"catch", "接住", "kætʃ", 0},
    {"celery", "芹菜", "ˈseləri", 0},
    {"cheek", "脸颊", "tʃiːk", 0},
    {"cheese", "奶酪", "tʃiːz", 0},
    {"cherry", "樱桃", "ˈtʃeri", 0},
    {"chess", "国际象棋", "tʃes", 0},
    {"chick", "小鸡", "tʃɪk", 0},
    {"chin", "下巴", "tʃɪn", 0},
    {"choose", "选择", "tʃuːz", 0},
    {"circle", "圆形", "ˈsɜːk(ə)l", 0},
    {"city", "城市", "ˈsɪti", 0},
    {"classmate", "同班同学", "ˈklɑːsmeɪt", 0},
    {"climb", "爬", "klaɪm", 0},
    {"close", "关闭", "kləʊz", 0},
    {"coconut", "椰子", "ˈkəʊkənʌt", 0},
    {"comb", "梳子", "kəʊm", 0},
    {"cookie", "曲奇饼", "ˈkʊki", 0},
    {"corn", "玉米", "kɔːn", 0},
    {"corner", "角落；拐角", "ˈkɔːnə(r)", 0},
    {"cost", "花费", "kɒst", 0},
    {"crab", "螃蟹", "kræb", 0},
    {"crocodile", "鳄鱼", "ˈkrɒkədaɪl", 0},
    {"cry", "哭", "kraɪ", 0},
    {"cucumber", "黄瓜", "ˈkjuːkʌmbə(r)", 0},
    {"cup", "杯子", "kʌp", 0},
    {"curtain", "窗帘", "ˈkɜːt(ə)n", 0},
    {"cut", "切，剪", "kʌt", 0},
    {"dancer", "舞蹈演员", "ˈdɑːnsə(r)", 0},
    {"deer", "鹿", "dɪə(r)", 0},
    {"desert", "沙漠", "ˈdezət", 0},
    {"dig", "挖", "dɪɡ", 0},
    {"doll", "玩偶", "dɒl", 0},
    {"dolphin", "海豚", "ˈdɒlfɪn", 0},
    {"donkey", "驴", "ˈdɒŋki", 0},
    {"dot", "点；圆点", "dɒt", 0},
    {"dragonfly", "蜻蜓", "ˈdræɡənflaɪ", 0},
    {"drum", "鼓", "drʌm", 0},
    {"dumpling", "饺子", "ˈdʌmplɪŋ", 0},
    {"eagle", "鹰", "ˈiːɡ(ə)l", 0},
    {"earth", "地球", "ɜːθ", 0},
    {"eggplant", "茄子", "ˈeɡplɑːnt", 0},
    {"eighth", "第八的", "eɪtθ", 0},
    {"elbow", "胳膊肘", "ˈelbəʊ", 0},
    {"engineer", "工程师", "ˌendʒɪˈnɪə(r)", 0},
    {"envelope", "信封", "ˈenvələʊp", 0},
    {"exam", "考试", "ɪɡˈzæm", 0},
    {"feather", "羽毛", "ˈfeðə(r)", 0},
    {"fence", "栅栏", "fens", 0},
    {"festival", "节日", "ˈfestɪvl; ˈfestəvəl", 0},
    {"field", "田地", "fiːld", 0},
    {"fifty", "五十", "ˈfɪfti", 0},
    {"finger", "手指", "ˈfɪŋɡə(r)", 0},
    {"fix", "修理", "fɪks", 0},
    {"flag", "旗子", "flæɡ", 0},
    {"flour", "面粉", "ˈflaʊə(r)", 0},
    {"flute", "长笛", "fluːt", 0},
    {"fog", "雾", "fɒɡ", 0},
    {"fold", "折叠", "fəʊld", 0},
    {"football", "足球运动", "ˈfʊtbɔːl", 0},
    {"fox", "狐狸", "fɒks", 0},
    {"free", "免费的", "friː", 0},
    {"frog", "青蛙", "frɒɡ", 0},
    {"garage", "车库", "ˈɡærɑːʒ", 0},
    {"garlic", "大蒜", "ˈɡɑːlɪk", 0},
    {"gate", "大门", "ɡeɪt", 0},
    {"gentle", "温柔的", "ˈdʒent(ə)l", 0},
    {"geography", "地理", "dʒiˈɒɡrəfi", 0},
    {"glue", "胶水", "ɡluː", 0},
    {"golden", "金制的", "ˈɡəʊldən", 0},
    {"goldfish", "金鱼", "ˈɡəʊldfɪʃ", 0},
    {"goose", "鹅", "ɡuːs", 0},
    {"grey", "灰色的", "ɡreɪ", 0},
    {"grow", "长大，种植", "ɡrəʊ", 0},
    {"guitar", "吉他", "ɡɪˈtɑː(r)", 0},
    {"Halloween", "万圣节前夕", "ˌhæləʊˈiːn", 0},
    {"handsome", "英俊的", "ˈhænsəm", 0},
    {"hang", "挂", "hæŋ", 0},
    {"heart", "心脏", "hɑːt", 0},
    {"hedgehog", "刺猬", "ˈhedʒhɒɡ", 0},
    {"helicopter", "直升机", "ˈhelɪkɒptə(r)", 0},
    {"history", "历史", "ˈhɪstri; ˈhɪstəri", 0},
    {"honest", "诚实的", "ˈɒnɪst", 0},
    {"honey", "蜂蜜", "ˈhʌni", 0},
    {"hour", "小时", "ˈaʊə(r)", 0},
    {"hug", "拥抱", "hʌɡ", 0},
    {"hundred", "一百", "ˈhʌndrəd", 0},
    {"hungry", "饥饿的", "ˈhʌŋɡri", 0},
    {"inside", "里面", "ˌɪnˈsaɪd", 0},
    {"invite", "邀请", "ɪnˈvaɪt", 0},
    {"jam", "果酱", "dʒæm", 0},
    {"jeans", "牛仔裤", "dʒiːnz", 0},
    {"jellyfish", "水母", "ˈdʒelifɪʃ", 0},
    {"jump", "跳", "dʒʌmp", 0},
    {"kangaroo", "袋鼠", "ˌkæŋɡəˈruː", 0},
    {"kick", "踢", "kɪk", 0},
    {"kiss", "亲吻", "kɪs", 0},
    {"knee", "膝盖", "niː", 0},
    {"knock", "敲", "nɒk", 0},
    {"koala", "树袋熊", "kəʊˈɑːlə", 0},
    {"lamb", "小羊", "læm", 0},
    {"laugh", "笑", "lɑːf", 0},
    {"lazy", "懒惰的", "ˈleɪzi", 0},
    {"lead", "带领", "liːd", 0},
    {"lemon", "柠檬", "ˈlemən", 0},
    {"leopard", "豹", "ˈlepəd", 0},
    {"lettuce", "生菜", "ˈletɪs", 0},
    {"lightning", "闪电", "ˈlaɪtnɪŋ", 0},
    {"line", "线", "laɪn", 0},
    {"lion", "狮子", "ˈlaɪən", 0},
    {"lip", "嘴唇", "lɪp", 0},
    {"listen", "听", "ˈlɪs(ə)n", 0},
    {"lock", "锁", "lɒk", 0},
    {"lonely", "孤单的", "ˈləʊnli", 0},
    {"lose", "丢失", "luːz", 0},
    {"luck", "运气", "lʌk", 0},
    {"mango", "芒果", "ˈmæŋɡəʊ", 0},
    {"market", "市场", "ˈmɑːkɪt", 0},
    {"maths", "数学", "mæθs", 0},
    {"meal", "一顿饭", "miːl", 0},
    {"medal", "奖牌", "ˈmed(ə)l", 0},
    {"melon", "瓜", "ˈmelən", 0},
    {"message", "消息", "ˈmesɪdʒ", 0},
    {"middle", "中间的", "ˈmɪd(ə)l", 0},
    {"minute", "分钟", "ˈmɪnɪt", 0},
    {"mirror", "镜子", "ˈmɪrə(r)", 0},
    {"mistake", "错误", "mɪˈsteɪk", 0},
    {"month", "月份", "mʌnθ", 0},
    {"mushroom", "蘑菇", "ˈmʌʃrʊm", 0},
    {"neck", "脖子", "nek", 0},
    {"neighbour", "邻居", "ˈneɪbə(r)", 0},
    {"nest", "鸟窝", "nest", 0},
    {"never", "从不", "ˈnevə(r)", 0},
    {"ninth", "第九", "naɪnθ", 0},
    {"noisy", "吵闹的", "ˈnɔɪzi", 0},
    {"ocean", "海洋", "ˈəʊʃ(ə)n", 0},
    {"octopus", "章鱼", "ˈɒktəpəs", 0},
    {"office", "办公室", "ˈɒfɪs", 0},
    {"olive", "橄榄", "ˈɒlɪv", 0},
    {"oval", "椭圆形的", "ˈəʊv(ə)l", 0},
    {"owl", "猫头鹰", "aʊl", 0},
    {"painter", "画家", "ˈpeɪntə(r)", 0},
    {"pancake", "薄煎饼", "ˈpænkeɪk", 0},
    {"parrot", "鹦鹉", "ˈpærət", 0},
    {"passenger", "乘客", "ˈpæsɪndʒə(r)", 0},
    {"patient", "能忍耐的", "ˈpeɪʃ(ə)nt", 0},
    {"pay", "付钱", "peɪ", 0},
    {"peach", "桃子", "piːtʃ", 0},
    {"peacock", "孔雀", "ˈpiːkɒk", 0},
    {"penguin", "企鹅", "ˈpeŋɡwɪn", 0},
    {"pepper", "胡椒粉", "ˈpepə(r)", 0},
    {"piano", "钢琴", "piˈænəʊ", 0},
    {"pillow", "枕头", "ˈpɪləʊ", 0},
    {"pineapple", "菠萝", "ˈpaɪnæp(ə)l", 0},
    {"player", "运动员", "ˈpleɪə(r)", 0},
    {"plum", "李子", "plʌm", 0},
    {"pocket", "口袋", "ˈpɒkɪt", 0},
    {"point", "指向", "pɔɪnt", 0},
    {"police", "警察", "pəˈliːs", 0},
    {"popcorn", "爆米花", "ˈpɒpkɔːn", 0},
    {"porridge", "粥", "ˈpɒrɪdʒ", 0},
    {"postcard", "明信片", "ˈpəʊstkɑːd", 0},
    {"practice", "练习", "ˈpræktɪs", 0},
    {"principal", "校长", "ˈprɪnsəp(ə)l", 0},
    {"prize", "奖品", "praɪz", 0},
    {"proud", "自豪的", "praʊd", 0},
    {"pumpkin", "南瓜", "ˈpʌmpkɪn", 0},
    {"purple", "紫色的", "ˈpɜːp(ə)l", 0},
    {"push", "推", "pʊʃ", 0},
    {"question", "问题", "ˈkwestʃən", 0},
    {"rainbow", "彩虹", "ˈreɪnbəʊ", 0},
    {"raincoat", "雨衣", "ˈreɪnkəʊt", 0},
    {"rectangle", "长方形", "ˈrektæŋɡl", 0},
    {"repair", "修理", "rɪˈpeə(r)", 0},
    {"reward", "奖励", "rɪˈwɔːd", 0},
    {"ride", "骑", "raɪd", 0},
    {"ring", "戒指", "rɪŋ", 0},
    {"road", "路", "rəʊd", 0},
    {"rocket", "火箭", "ˈrɒkɪt", 0},
    {"roof", "屋顶", "ruːf", 0},
    {"round", "圆形的", "raʊnd", 0},
    {"rude", "没礼貌的", "ruːd", 0},
    {"run", "跑", "rʌn", 0},
    {"salt", "盐", "sɔːlt; sɒlt", 0},
    {"salty", "咸的", "ˈsɔːlti", 0},
    {"sand", "沙子", "sænd", 0},
    {"sausage", "香肠", "ˈsɒsɪdʒ", 0},
    {"scared", "害怕的", "skeəd", 0},
    {"scissors", "剪刀", "ˈsɪzəz", 0},
    {"score", "得分", "skɔː(r)", 0},
    {"seafood", "海鲜", "ˈsiːfuːd", 0},
    {"seal", "海豹", "siːl", 0},
    {"sell", "卖", "sel", 0},
    {"serious", "严重的", "ˈsɪəriəs", 0},
    {"seventh", "第七", "ˈsev(ə)nθ", 0},
    {"shake", "摇动", "ʃeɪk", 0},
    {"shark", "鲨鱼", "ʃɑːk", 0},
    {"sharpener", "卷笔刀", "ˈʃɑːpnə(r)", 0},
    {"shelf", "架子", "ʃelf", 0},
    {"shoulder", "肩膀", "ˈʃəʊldə(r)", 0},
    {"shout", "喊", "ʃaʊt", 0},
    {"shrimp", "虾", "ʃrɪmp", 0},
    {"silver", "银；银色的", "ˈsɪlvə(r)", 0},
    {"singer", "歌手", "ˈsɪŋə(r)", 0},
    {"sixth", "第六", "sɪksθ", 0},
    {"skate", "滑冰", "skeɪt", 0},
    {"ski", "滑雪板", "skiː", 0},
    {"skin", "皮肤", "skɪn", 0},
    {"sky", "天空", "skaɪ", 0},
    {"sleep", "睡觉", "sliːp", 0},
    {"smile", "微笑", "smaɪl", 0},
    {"snack", "零食", "snæk", 0},
    {"snail", "蜗牛", "sneɪl", 0},
    {"snake", "蛇", "sneɪk", 0},
    {"soap", "肥皂", "səʊp", 0},
    {"sour", "酸的", "ˈsaʊə(r)", 0},
    {"sparrow", "麻雀", "ˈspærəʊ", 0},
    {"spicy", "辣的", "ˈspaɪsi", 0},
    {"spider", "蜘蛛", "ˈspaɪdə(r)", 0},
    {"square", "正方形的", "skweə(r)", 0},
    {"squirrel", "松鼠", "ˈskwɪrəl", 0},
    {"stairs", "楼梯", "steəz", 0},
    {"stamp", "邮票", "stæmp", 0},
    {"station", "车站", "ˈsteɪʃ(ə)n", 0},
    {"steak", "牛排", "steɪk", 0},
    {"stomach", "胃", "ˈstʌmək", 0},
    {"stone", "石头", "stəʊn", 0},
    {"storm", "暴风雨", "stɔːm", 0},
    {"stream", "小溪", "striːm", 0},
    {"subject", "科目", "ˈsʌbdʒɪkt", 0},
    {"sugar", "糖", "ˈʃʊɡə(r)", 0},
    {"sunrise", "日出", "ˈsʌnraɪz", 0},
    {"sunset", "日落", "ˈsʌnset", 0},
    {"supper", "晚餐", "ˈsʌpə(r)", 0},
    {"surprised", "惊讶的", "səˈpraɪzd", 0},
    {"swan", "天鹅", "swɒn", 0},
    {"sweep", "打扫", "swiːp", 0},
    {"team", "队；团队", "tiːm", 0},
    {"temperature", "温度", "ˈtemprətʃə(r)", 0},
    {"tennis", "网球", "ˈtenɪs", 0},
    {"tenth", "第十", "tenθ", 0},
    {"term", "学期", "tɜːm", 0},
    {"test", "测验", "test", 0},
    {"thousand", "一千", "ˈθaʊz(ə)nd", 0},
    {"throw", "扔", "θrəʊ", 0},
    {"thumb", "拇指", "θʌm", 0},
    {"thunder", "雷", "ˈθʌndə(r)", 0},
    {"ticket", "票", "ˈtɪkɪt", 0},
    {"tie", "系", "taɪ", 0},
    {"toe", "脚趾", "təʊ", 0},
    {"tongue", "舌头", "tʌŋ", 0},
    {"tooth", "牙齿", "tuːθ", 0},
    {"tortoise", "乌龟", "ˈtɔːtəs", 0},
    {"towel", "毛巾", "ˈtaʊəl", 0},
    {"town", "城镇", "taʊn", 0},
    {"triangle", "三角形", "ˈtraɪæŋɡ(ə)l", 0},
    {"truck", "卡车", "trʌk", 0},
    {"trumpet", "小号", "ˈtrʌmpɪt", 0},
    {"turtle", "海龟", "ˈtɜːt(ə)l", 0},
    {"ugly", "丑的", "ˈʌɡli", 0},
    {"uniform", "校服", "ˈjuːnɪfɔːm", 0},
    {"valley", "山谷", "ˈvæli", 0},
    {"violin", "小提琴", "ˌvaɪəˈlɪn", 0},
    {"volcano", "火山", "vɒlˈkeɪnəʊ", 0},
    {"volleyball", "排球运动", "ˈvɒlibɔːl", 0},
    {"waiter", "服务员", "ˈweɪtə(r)", 0},
    {"waterfall", "瀑布", "ˈwɔːtəfɔːl", 0},
    {"wave", "挥手", "weɪv", 0},
    {"weak", "弱的", "wiːk", 0},
    {"week", "星期", "wiːk", 0},
    {"whale", "鲸", "weɪl", 0},
    {"whisper", "小声说", "ˈwɪspə(r)", 0},
    {"wing", "翅膀", "wɪŋ", 0},
    {"wise", "明智的", "waɪz", 0},
    {"wish", "愿望", "wɪʃ", 0},
    {"wolf", "狼", "wʊlf", 0},
    {"worm", "虫子", "wɜːm", 0},
    {"wrist", "手腕", "rɪst", 0},
    {"write", "写", "raɪt", 0},
    {"yogurt", "酸奶", "ˈjɒɡət", 0},
    {"zebra", "斑马", "ˈzebrə", 0},
    {"T-shirt", "T恤", "ˈtiː ʃɜːt", 0},
    {"afternoon", "下午", "ˌɑːftəˈnuːn", 0},
    {"age", "年龄", "eɪdʒ", 0},
    {"art", "美术", "ɑːt", 0},
    {"Chinese", "中国的", "ˌtʃaɪˈniːz", 0},
    {"English", "英国的", "ˈɪŋɡlɪʃ", 0},
    {"PE", "体育课", "ˌpiː ˈiː", 0},
    {"Australia", "澳大利亚", "ɒˈstreɪliə", 0},
    {"Disneyland", "迪斯尼乐园", "ˈdɪznilænd", 0},
    {"advice", "建议", "ədˈvaɪs", 0},
    {"Africa", "非洲", "ˈæfrɪkə", 0},
    {"airport", "机场", "ˈeəpɔːt", 0},
    {"around", "周围", "əˈraʊnd", 0},
    {"arrive", "到达", "əˈraɪv", 0},
    {"artist", "艺术家", "ˈɑːtɪst", 0},
    {"Asia", "亚洲", "ˈeɪʒə", 0},
    {"French", "法国的", "frentʃ", 0},
    {"Toronto", "多伦多", "təˈrɒntəʊ", 0},
    {"ruler", "尺子", "'ruːlə", 1},
    {"pencil", "铅笔", "'pens(ə)l; -sɪl", 1},
    {"eraser", "橡皮", "ɪ'reɪzə", 1},
    {"crayon", "蜡笔", "ˈkreɪən", 1},
    {"bag", "包", "bæg", 1},
    {"pen", "钢笔", "pen", 1},
    {"pencil box", "铅笔盒", "'pɛnsl bɑks", 1},
    {"book", "书", "bʊk", 1},
    {"no", "不；没有", "nəʊ", 1},
    {"your", "你的", "jɔ:(r)", 1},
    {"red", "红色", "red", 1},
    {"green", "绿色", "griːn", 1},
    {"yellow", "黄色", "'jeləʊ", 1},
    {"blue", "蓝色", "bluː", 1},
    {"black", "黑色", "blæk", 1},
    {"brown", "棕色", "braʊn", 1},
    {"white", "白色", "waɪt", 1},
    {"orange", "橙色", "'ɒrɪn(d)ʒ", 1},
    {"OK", "好；行", "", 1},
    {"mum", "妈妈", "mʌm", 1},
    {"face", "脸", "feɪs", 1},
    {"ear", "耳朵", "ɪə", 1},
    {"eye", "眼睛", "aɪ", 1},
    {"nose", "鼻子", "nəʊz", 1},
    {"mouth", "嘴", "maʊθ", 1},
    {"arm", "胳膊", "ɑːm", 1},
    {"hand", "手", "hænd", 1},
    {"head", "头", "hed", 1},
    {"body", "身体", "'bɒdɪ", 1},
    {"leg", "腿", "leg", 1},
    {"foot", "脚", "fʊt", 1},
    {"school", "学校", "skuːl", 1},
    {"duck", "鸭子", "dʌk", 1},
    {"pig", "猪", "pɪg", 1},
    {"cat", "猫", "kæt", 1},
    {"bear", "熊", "beə", 1},
    {"dog", "狗", "dɒg", 1},
    {"elephant", "大象", "'elɪf(ə)nt", 1},
    {"monkey", "猴子", "'mʌŋkɪ", 1},
    {"bird", "鸟", "bɜːd", 1},
    {"tiger", "老虎", "'taɪgə", 1},
    {"panda", "大熊猫", "'pændə", 1},
    {"zoo", "动物园", "zuː", 1},
    {"funny", "滑稽的", "'fʌnɪ", 1},
    {"bread", "面包", "bred", 1},
    {"juice", "果汁", "dʒuːs", 1},
    {"egg", "蛋", "eg", 1},
    {"milk", "牛奶", "mɪlk", 1},
    {"water", "水", "'wɔːtə", 1},
    {"cake", "蛋糕", "keɪk", 1},
    {"fish", "鱼", "fɪʃ", 1},
    {"rice", "米饭", "raɪs", 1},
    {"one", "一", "wʌn", 1},
    {"two", "二", "tuː", 1},
    {"three", "三", "θriː", 1},
    {"four", "四", "fɔː", 1},
    {"five", "五", "faɪv", 1},
    {"six", "六", "sɪks", 1},
    {"seven", "七", "'sev(ə)n", 1},
    {"eight", "八", "eɪt", 1},
    {"nine", "九", "naɪn", 1},
    {"ten", "十", "ten", 1},
    {"brother", "哥哥；弟弟", "'brʌðə", 1},
    {"plate", "盘子", "pleɪt", 1},
    {"UK", "英国", "", 2},
    {"Canada", "加拿大", "'kænədə", 2},
    {"USA", "美国", "", 2},
    {"China", "中国", "ˈtʃaɪnə", 2},
    {"she", "她", "ʃiː", 2},
    {"student", "学生", "'stjuːd(ə)nt", 2},
    {"pupil", "小学生", "'pjuːpɪl; -p(ə)l", 2},
    {"he", "他", "hiː", 2},
    {"teacher", "教师", "'tiːtʃə", 2},
    {"boy", "男孩", "bɒɪ", 2},
    {"and", "和", "ənd; (ə)n; ænd", 2},
    {"girl", "女孩", "gɜːl", 2},
    {"new", "新的", "njuː", 2},
    {"friend", "朋友", "frend", 2},
    {"today", "今天", "tə'deɪ", 2},
    {"father", "父亲", "'fɑːðə", 2},
    {"dad", "爸爸", "dæd", 2},
    {"man", "男人", "mæn", 2},
    {"woman", "女人", "'wʊmən", 2},
    {"mother", "母亲", "'mʌðə", 2},
    {"sister", "姐姐；妹妹", "'sɪstə", 2},
    {"grandmother", "祖母", "'græn(d)mʌðə", 2},
    {"grandma", "祖母", "'græn(d)mɑː", 2},
    {"grandfather", "祖父", "'græn(d)fɑːðə", 2},
    {"grandpa", "祖父", "ˈgrænpɑ:", 2},
    {"family", "家庭", "ˈfæməlɪ", 2},
    {"thin", "瘦的", "θɪn", 2},
    {"fat", "胖的", "fæt", 2},
    {"tall", "高的", "tɔːl", 2},
    {"short", "矮的", "ʃɔːt", 2},
    {"long", "长的", "lɒŋ", 2},
    {"small", "小的", "smɔːl", 2},
    {"big", "大的", "bɪg", 2},
    {"giraffe", "长颈鹿", "dʒɪˈrɑ:f", 2},
    {"so", "这么", "səʊ", 2},
    {"children", "儿童(复数)", "'tʃɪldrən", 2},
    {"child", "儿童", "tʃaɪld", 2},
    {"tail", "尾巴", "teɪl", 2},
    {"on", "在……上", "ɒn", 2},
    {"in", "在……里", "ɪn", 2},
    {"under", "在……下面", "'ʌndə", 2},
    {"chair", "椅子", "tʃeə", 2},
    {"desk", "书桌", "desk", 2},
    {"cap", "帽子", "kæp", 2},
    {"ball", "球", "bɔːl", 2},
    {"car", "小汽车", "kɑː", 2},
    {"boat", "小船", "bəʊt", 2},
    {"map", "地图", "mæp", 2},
    {"toy", "玩具", "tɒɪ", 2},
    {"box", "盒子", "bɒks", 2},
    {"pear", "梨", "peə", 2},
    {"apple", "苹果", "'æp(ə)l", 2},
    {"banana", "香蕉", "bə'nɑːnə", 2},
    {"watermelon", "西瓜", "'wɔːtəmelən", 2},
    {"strawberry", "草莓", "'strɔːb(ə)rɪ", 2},
    {"grape", "葡萄", "greɪp", 2},
    {"buy", "买", "baɪ", 2},
    {"fruit", "水果", "fruːt", 2},
    {"eleven", "十一", "ɪ'lev(ə)n", 2},
    {"twelve", "十二", "twelv", 2},
    {"thirteen", "十三", "θɜː'tiːn; 'θɜːtiːn", 2},
    {"fourteen", "十四", "fɔː'tiːn; 'fɔːtiːn", 2},
    {"fifteen", "十五", "fɪf'tiːn; 'fɪftiːn", 2},
    {"sixteen", "十六", "sɪks'tiːn; 'sɪkstiːn", 2},
    {"seventeen", "十七", "sev(ə)n'tiːn; 'sev(ə)ntiːn", 2},
    {"eighteen", "十八", "eɪ'tiːn; 'eɪtiːn", 2},
    {"nineteen", "十九", "naɪn'tiːn; 'naɪntiːn", 2},
    {"twenty", "二十", "'twentɪ", 2},
    {"kite", "风筝", "kaɪt", 2},
    {"beautiful", "美丽的", "ˈbju:tɪfl", 2},
    {"classroom", "教室", "'klɑːsruːm; -rʊm", 3},
    {"window", "窗户", "'wɪndəʊ", 3},
    {"blackboard", "黑板", "'blækbɔːd", 3},
    {"light", "电灯", "laɪt", 3},
    {"picture", "图画", "'pɪktʃə", 3},
    {"door", "门", "dɔː", 3},
    {"teacher's desk", "讲台", "", 3},
    {"computer", "计算机", "kəm'pjuːtə", 3},
    {"fan", "风扇", "fæn", 3},
    {"wall", "墙壁", "wɔːl", 3},
    {"floor", "地板", "flɔː", 3},
    {"really", "真的", "'rɪəlɪ", 3},
    {"near", "在……附近", "nɪə", 3},
    {"TV", "电视", "ˌti: ˈvi:", 3},
    {"clean", "打扫", "kliːn", 3},
    {"help", "帮助", "help", 3},
    {"schoolbag", "书包", "'skuːlbæɡ", 3},
    {"maths book", "数学书", "", 3},
    {"English book", "英语书", "", 3},
    {"Chinese book", "语文书", "", 3},
    {"storybook", "故事书", "'stɔːrɪbʊk", 3},
    {"candy", "糖果", "'kændɪ", 3},
    {"notebook", "笔记本", "'nəʊtbʊk", 3},
    {"key", "钥匙", "kiː", 3},
    {"wow", "哇", "waʊ", 3},
    {"lost", "丢失(过去式)", "lɒst", 3},
    {"so much", "非常地", "", 3},
    {"cute", "可爱的", "kjuːt", 3},
    {"strong", "强壮的", "strɒŋ", 3},
    {"friendly", "友好的", "ˈfrendlɪ", 3},
    {"quiet", "安静的", "'kwaɪət", 3},
    {"hair", "头发", "heə", 3},
    {"shoe", "鞋", "ʃuː", 3},
    {"glasses", "眼镜", "'glɑːsɪz", 3},
    {"his", "他的", "hɪz", 3},
    {"or", "或者", "ɔː", 3},
    {"right", "对的", "raɪt", 3},
    {"hat", "帽子", "hæt", 3},
    {"her", "她的", "hɜː", 3},
    {"bedroom", "卧室", "'bedruːm; -rʊm", 3},
    {"living room", "客厅", "'lɪvɪŋ ru:m", 3},
    {"study", "书房", "'stʌdɪ", 3},
    {"kitchen", "厨房", "'kɪtʃɪn; -tʃ(ə)n", 3},
    {"bathroom", "浴室", "'bɑːθruːm; -rʊm", 3},
    {"bed", "床", "bed", 3},
    {"phone", "电话", "fəʊn", 3},
    {"table", "桌子", "'teɪb(ə)l", 3},
    {"sofa", "长沙发", "'səʊfə", 3},
    {"fridge", "冰箱", "frɪdʒ", 3},
    {"find", "找到", "faɪnd", 3},
    {"them", "他们", "ðem; ðəm", 3},
    {"beef", "牛肉", "biːf", 3},
    {"chicken", "鸡肉", "'tʃɪkɪn", 3},
    {"noodles", "面条", "ˈnu:dlz", 3},
    {"soup", "汤", "suːp", 3},
    {"vegetable", "蔬菜", "ˈvedʒtəbl", 3},
    {"chopsticks", "筷子", "'tʃɒpstɪks", 3},
    {"bowl", "碗", "bəʊl", 3},
    {"fork", "餐叉", "fɔːk", 3},
    {"knife", "刀", "naɪf", 3},
    {"spoon", "汤匙", "spuːn", 3},
    {"dinner", "正餐", "'dɪnə", 3},
    {"ready", "准备好", "'redɪ", 3},
    {"help yourself", "请自便", "", 3},
    {"pass", "传递；通过", "pɑːs", 3},
    {"try", "试", "traɪ", 3},
    {"parents", "父母", "'peərənts", 3},
    {"cousin", "同辈表亲", "'kʌz(ə)n", 3},
    {"uncle", "叔叔", "'ʌŋk(ə)l", 3},
    {"aunt", "阿姨", "ɑːnt", 3},
    {"baby brother", "小弟弟", "", 3},
    {"doctor", "医生", "'dɒktə", 3},
    {"cook", "厨师", "kʊk", 3},
    {"driver", "司机", "'draɪvə", 3},
    {"farmer", "农民", "'fɑːmə", 3},
    {"nurse", "护士", "nɜːs", 3},
    {"people", "人们", "'piːp(ə)l", 3},
    {"but", "但是", "bʌt; bət", 3},
    {"little", "小的", "'lɪt(ə)l", 3},
    {"puppy", "小狗", "'pʌpɪ", 3},
    {"football player", "足球运动员", "", 3},
    {"job", "工作", "dʒɒb", 3},
    {"basketball", "篮球", "'bɑːskɪtbɔːl", 3},
    {"first floor", "一楼", "", 4},
    {"second floor", "二楼", "", 4},
    {"teacher's office", "教师办公室", "", 4},
    {"library", "图书馆", "ˈlaɪbrərɪ", 4},
    {"playground", "操场", "'pleɪgraʊnd", 4},
    {"computer room", "计算机房", "", 4},
    {"art room", "美术教室", "", 4},
    {"music room", "音乐教室", "", 4},
    {"next to", "紧邻", "", 4},
    {"homework", "作业", "'həʊmwɜːk", 4},
    {"class", "班级", "klɑːs", 4},
    {"forty", "四十", "'fɔːtɪ", 4},
    {"way", "方向", "weɪ", 4},
    {"breakfast", "早餐", "'brekfəst", 4},
    {"English class", "英语课", "", 4},
    {"lunch", "午饭", "lʌn(t)ʃ", 4},
    {"music class", "音乐课", "", 4},
    {"PE class", "体育课", "", 4},
    {"get up", "起床", "", 4},
    {"go to school", "上学", "", 4},
    {"go home", "回家", "", 4},
    {"go to bed", "去睡觉", "", 4},
    {"over", "结束", "'əʊvə", 4},
    {"now", "现在", "naʊ", 4},
    {"o'clock", "……点钟", "ə'klɒk", 4},
    {"kid", "小孩", "kɪd", 4},
    {"thirty", "三十", "'θɜːtɪ", 4},
    {"hurry up", "快点", "'hʌrɪ ʌp", 4},
    {"come on", "加油", "", 4},
    {"just a minute", "稍等一会儿", "", 4},
    {"cold", "冷的", "kəʊld", 4},
    {"cool", "凉的", "kuːl", 4},
    {"warm", "温暖的", "wɔːm", 4},
    {"hot", "热的", "hɒt", 4},
    {"sunny", "阳光充足的", "'sʌnɪ", 4},
    {"windy", "多风的", "'wɪndɪ", 4},
    {"cloudy", "多云的", "'klaʊdɪ", 4},
    {"snowy", "下雪的", "'snəʊɪ", 4},
    {"rainy", "阴雨的", "'reɪnɪ", 4},
    {"outside", "在户外", "aʊt'saɪd; 'aʊtsaɪd", 4},
    {"be careful", "小心", "", 4},
    {"weather", "天气", "'weðə", 4},
    {"New York", "纽约", "", 4},
    {"how about...", "怎么样？", "", 4},
    {"degree", "度；度数", "dɪ'griː", 4},
    {"world", "世界", "wɜːld", 4},
    {"London", "伦敦", "ˈlʌndən", 4},
    {"Moscow", "莫斯科", "'mɔskəʊ", 4},
    {"Singapore", "新加坡城", "ˌsɪŋgə'pɔ:", 4},
    {"Sydney", "悉尼", "ˈsɪdnɪ", 4},
    {"fly", "飞", "flaɪ", 4},
    {"love", "爱", "lʌv", 4},
    {"tomato", "西红柿", "tə'mɑːtəʊ", 4},
    {"potato", "马铃薯", "pə'teɪtəʊ", 4},
    {"green beans", "豆角", "", 4},
    {"carrot", "胡萝卜", "'kærət", 4},
    {"horse", "马", "hɔːs", 4},
    {"cow", "牛", "kaʊ", 4},
    {"sheep", "绵羊", "ʃiːp", 4},
    {"hen", "母鸡", "hen", 4},
    {"these", "这些", "ðiːz", 4},
    {"yum", "味道好", "jʌm", 4},
    {"animal", "动物", "'ænɪm(ə)l", 4},
    {"those", "那些", "ðəʊz", 4},
    {"garden", "花园", "'gɑːd(ə)n", 4},
    {"farm", "农场", "fɑːm", 4},
    {"goat", "山羊", "gəʊt", 4},
    {"eat", "吃", "iːt", 4},
    {"clothes", "服装", "kləʊ(ð)z", 4},
    {"pants", "裤子", "pæn(t)s", 4},
    {"dress", "连衣裙", "dres", 4},
    {"skirt", "女裙", "skɜːt", 4},
    {"coat", "大衣", "kəʊt", 4},
    {"sweater", "毛衣", "'swetə", 4},
    {"sock", "短袜", "sɒk", 4},
    {"shorts", "短裤", "ʃɔːts", 4},
    {"jacket", "夹克衫", "'dʒækɪt", 4},
    {"shirt", "衬衫", "ʃɜːt", 4},
    {"yours", "你的", "jɔːz; jʊəz", 4},
    {"whose", "谁的", "huːz", 4},
    {"mine", "我的", "maɪn", 4},
    {"pack", "收拾", "pæk", 4},
    {"wait", "等待", "weɪt", 4},
    {"glove", "手套", "glʌv", 4},
    {"scarf", "围巾", "skɑːf", 4},
    {"umbrella", "伞", "ʌm'brelə", 4},
    {"sunglasses", "太阳镜", "'sʌnglɑːsɪz", 4},
    {"pretty", "美丽的", "'prɪtɪ", 4},
    {"expensive", "贵的", "ɪkˈspensɪv", 4},
    {"cheap", "便宜的", "tʃiːp", 4},
    {"nice", "好的", "naɪs", 4},
    {"try on", "试穿", "", 4},
    {"size", "尺码", "saɪz", 4},
    {"of course", "当然", "", 4},
    {"too", "太；也", "tuː", 4},
    {"just", "正好", "dʒʌst", 4},
    {"how much", "多少钱", "haʊ mʌtʃ", 4},
    {"eighty", "八十", "'eɪtɪ", 4},
    {"dollar", "美元", "'dɒlə", 4},
    {"sale", "特价销售", "seɪl", 4},
    {"more", "更多的", "mɔː", 4},
    {"us", "我们", "əs; ʌs", 4},
    {"old", "老的", "əʊld", 5},
    {"young", "年轻的", "jʌŋ", 5},
    {"kind", "体贴的", "kaɪnd", 5},
    {"strict", "严厉的", "strɪkt", 5},
    {"polite", "有礼貌的", "pə'laɪt", 5},
    {"hard-working", "努力的", "ˈhɑːdˈwɜːkɪŋ", 5},
    {"helpful", "有用的", "'helpfʊl; -f(ə)l", 5},
    {"clever", "聪明的", "'klevə", 5},
    {"shy", "羞怯的", "ʃaɪ", 5},
    {"know", "知道", "nəʊ", 5},
    {"our", "我们的", "aʊə", 5},
    {"Ms", "女士", "", 5},
    {"will", "将要", "wɪl", 5},
    {"sometimes", "有时", "'sʌmtaɪmz", 5},
    {"robot", "机器人", "'rəʊbɒt", 5},
    {"him", "他", "hɪm", 5},
    {"speak", "说", "spiːk", 5},
    {"finish", "完成", "'fɪnɪʃ", 5},
    {"Monday", "星期一", "ˈmʌndeɪ; ˈmʌndi", 5},
    {"Tuesday", "星期二", "'tjuːzdeɪ; -dɪ", 5},
    {"Wednesday", "星期三", "ˈwenzdɪ", 5},
    {"Thursday", "星期四", "'θɜːzdeɪ; -dɪ", 5},
    {"Friday", "星期五", "ˈfraɪdeɪ", 5},
    {"Saturday", "星期六", "ˈsætədɪ; -deɪ", 5},
    {"Sunday", "星期日", "ˈsʌndeɪ; ˈsʌndi", 5},
    {"weekend", "周末", "wiːkˈɛnd", 5},
    {"wash", "洗", "wɒʃ", 5},
    {"wash my clothes", "洗我的衣服", "", 5},
    {"watch", "看", "wɒtʃ", 5},
    {"watch TV", "看电视", "", 5},
    {"do", "做", "duː", 5},
    {"do homework", "做作业", "", 5},
    {"read", "读", "ri:d;red", 5},
    {"read books", "看书", "", 5},
    {"play", "玩", "pleɪ", 5},
    {"play football", "踢足球", "", 5},
    {"cooking", "烹饪", "'kʊkɪŋ", 5},
    {"often", "时常", "'ɒf(tə)n", 5},
    {"park", "公园", "pɑːk", 5},
    {"tired", "疲倦的", "taɪəd", 5},
    {"sport", "体育运动", "spɔːt", 5},
    {"play sports", "做体育运动", "", 5},
    {"should", "应该", "ʃəd; strong form ʃʊd", 5},
    {"every", "每一个", "'evrɪ", 5},
    {"day", "一天", "deɪ", 5},
    {"schedule", "日程安排", "ˈʃedju:l", 5},
    {"sandwich", "三明治", "'sæn(d)wɪdʒ; -wɪtʃ", 5},
    {"salad", "沙拉", "'sæləd", 5},
    {"hamburger", "汉堡包", "ˈhæmbɜ:gə", 5},
    {"ice cream", "冰淇淋", "aɪs kri:m", 5},
    {"tea", "茶", "tiː", 5},
    {"fresh", "新鲜的", "freʃ", 5},
    {"healthy", "健康的", "'helθɪ", 5},
    {"delicious", "美味的", "dɪ'lɪʃəs", 5},
    {"sweet", "甜的", "swiːt", 5},
    {"drink", "喝", "drɪŋk", 5},
    {"thirsty", "渴的", "'θɜːstɪ", 5},
    {"favourite", "特别喜欢的", "'feɪv(ə)rɪt", 5},
    {"food", "食物", "fuːd", 5},
    {"Dear", "亲爱的", "dɪə", 5},
    {"onion", "洋葱", "'ʌnjən", 5},
    {"sing", "唱", "sɪŋ", 5},
    {"song", "歌曲", "sɒŋ", 5},
    {"sing English songs", "唱英文歌曲", "", 5},
    {"play the pipa", "弹琵琶", "", 5},
    {"kung fu", "功夫", ",kʌŋ'fu:", 5},
    {"do kung fu", "练武术", "", 5},
    {"dance", "跳舞", "dɑːns", 5},
    {"draw", "画", "drɔː", 5},
    {"cartoon", "漫画", "kɑː'tuːn", 5},
    {"draw cartoons", "画漫画", "", 5},
    {"swim", "游泳", "swɪm", 5},
    {"play basketball", "打篮球", "", 5},
    {"ping-pong", "乒乓球", "", 5},
    {"play ping-pong", "打乒乓球", "", 5},
    {"speak English", "说英语", "", 5},
    {"we'll", "我们将……", "wel", 5},
    {"party", "聚会", "'pɑːtɪ", 5},
    {"next", "下一个的", "nekst", 5},
    {"wonderful", "极好的", "ˈwʌndə(r)fl", 5},
    {"learn", "学习", "lɜːn", 5},
    {"any", "任何的", "'enɪ", 5},
    {"problem", "问题", "'prɒbləm", 5},
    {"no problem", "没问题", "", 5},
    {"want", "要", "wɒnt", 5},
    {"send", "邮寄", "send", 5},
    {"email", "电子邮件", "'iːmeɪl", 5},
    {"clock", "时钟", "klɒk", 5},
    {"plant", "植物", "plɑːnt", 5},
    {"bottle", "瓶子", "'bɒt(ə)l", 5},
    {"water bottle", "水瓶", "", 5},
    {"bike", "自行车", "baɪk", 5},
    {"photo", "照片", "'fəʊtəʊ", 5},
    {"front", "正面", "frʌnt", 5},
    {"in front of", "在……前面", "ɪn frʌnt əv", 5},
    {"between", "在……中间", "bɪ'twiːn", 5},
    {"above", "在……上面", "ə'bʌv", 5},
    {"beside", "在旁边", "bɪ'saɪd", 5},
    {"behind", "在……后面", "bɪ'haɪnd", 5},
    {"grandparent", "祖父母", "'græn(d)peər(ə)nt", 5},
    {"their", "他们的", "ðeə", 5},
    {"house", "房子", "haʊs", 5},
    {"lot", "大量", "lɒt", 5},
    {"lots of", "大量", "", 5},
    {"flower", "花", "'flaʊə", 5},
    {"move", "搬家", "muːv", 5},
    {"dirty", "肮脏的", "'dɜːtɪ", 5},
    {"everywhere", "处处", "'evrɪweə", 5},
    {"mouse", "老鼠", "maʊs", 5},
    {"live", "住", "laɪv；lɪv", 5},
    {"nature", "自然界", "'neɪtʃə", 5},
    {"forest", "森林", "'fɒrɪst", 5},
    {"river", "河", "'rɪvə", 5},
    {"lake", "湖", "leɪk", 5},
    {"mountain", "山", "ˈmaʊntən", 5},
    {"hill", "小山", "hɪl", 5},
    {"tree", "树", "triː", 5},
    {"bridge", "桥", "brɪdʒ", 5},
    {"building", "建筑", "'bɪldɪŋ", 5},
    {"village", "村庄", "'vɪlɪdʒ", 5},
    {"boating", "划船", "'bəʊtɪŋ", 5},
    {"go boating", "去划船", "", 5},
    {"aren't", "不是", "ɑ:nt", 5},
    {"rabbit", "兔", "'ræbɪt", 5},
    {"high", "高的", "haɪ", 5},
    {"eat breakfast", "吃早饭", "it brɛkfəst", 6},
    {"have...class", "上……课", "", 6},
    {"exercise", "活动", "'eksəsaɪz", 6},
    {"do morning exercise", "做早操", "", 6},
    {"eat dinner", "吃晚饭", "", 6},
    {"clean my room", "打扫我的房间", "", 6},
    {"go for a walk", "散步", "", 6},
    {"go shopping", "购物", "", 6},
    {"take", "拿", "teɪk", 6},
    {"dancing", "跳舞(ing形式)", "'dɑːnsɪŋ", 6},
    {"take a dancing class", "上舞蹈课", "", 6},
    {"when", "什么时候", "wen", 6},
    {"after", "在……之后", "'ɑːftə", 6},
    {"start", "开始", "stɑːt", 6},
    {"usually", "通常地", "ˈjuːʒʊəlɪ", 6},
    {"Spain", "西班牙", "spein", 6},
    {"late", "晚的；迟到", "leɪt", 6},
    {"a.m.", "上午", "", 6},
    {"p.m.", "下午", "", 6},
    {"why", "为什么", "waɪ", 6},
    {"shop", "购物", "ʃɒp", 6},
    {"work", "工作", "wɜːk", 6},
    {"last", "上一个的", "lɑːst", 6},
    {"sound", "听起来好像", "saʊnd", 6},
    {"also", "也；还", "'ɔːlsəʊ", 6},
    {"busy", "忙的", "'bɪzɪ", 6},
    {"need", "需要", "niːd", 6},
    {"letter", "信", "'letə", 6},
    {"island", "岛", "'aɪlənd", 6},
    {"always", "总是", "ˈɔ:lweɪz", 6},
    {"cave", "山洞", "keɪv", 6},
    {"go swimming", "去游泳", "", 6},
    {"win", "获胜", "wɪn", 6},
    {"spring", "春天", "sprɪŋ", 6},
    {"summer", "夏天", "'sʌmə", 6},
    {"autumn", "秋天", "'ɔːtəm", 6},
    {"winter", "冬天", "'wɪntə", 6},
    {"season", "季节", "'siːz(ə)n", 6},
    {"picnic", "野餐", "'pɪknɪk", 6},
    {"go on a picnic", "去野餐", "", 6},
    {"pick", "摘", "pɪk", 6},
    {"pick apples", "摘苹果", "", 6},
    {"snowman", "雪人", "'snəʊmæn", 6},
    {"make a snowman", "堆雪人", "", 6},
    {"which", "哪一个", "wɪtʃ", 6},
    {"best", "最好的", "best", 6},
    {"snow", "雪", "snəʊ", 6},
    {"good job", "做得好", "", 6},
    {"because", "因为", "bɪ'kɒz", 6},
    {"vacation", "假期", "vəˈkeɪʃn", 6},
    {"all", "全部", "ɔːl", 6},
    {"pink", "粉色", "pɪŋk", 6},
    {"lovely", "可爱的", "'lʌvlɪ", 6},
    {"leaf", "叶子", "liːf", 6},
    {"fall", "落下", "fɔːl", 6},
    {"paint", "绘画", "peɪnt", 6},
    {"January", "一月", "'dʒænjʊ(ə)rɪ", 6},
    {"February", "二月", "ˈfebrʊərɪ", 6},
    {"March", "三月", "mɑːtʃ", 6},
    {"April", "四月", "'eɪprəl", 6},
    {"May", "五月", "meɪ", 6},
    {"June", "六月", "dʒu:n", 6},
    {"July", "七月", "dʒʊˈlaɪ", 6},
    {"August", "八月", "ɔ:ˈgʌst", 6},
    {"September", "九月", "sep'tembə", 6},
    {"October", "十月", "ɒk'təʊbə", 6},
    {"November", "十一月", "nə(ʊ)'vembə", 6},
    {"December", "十二月", "dɪ'sembə", 6},
    {"few", "不多", "fjuː", 6},
    {"a few", "一些", "", 6},
    {"thing", "事情", "θɪŋ", 6},
    {"meet", "见面", "miːt", 6},
    {"sports meet", "运动会", "", 6},
    {"Easter", "复活节", "'i:stə", 6},
    {"trip", "旅行", "trɪp", 6},
    {"year", "年", "jɪə; jɜː", 6},
    {"contest", "比赛", "'kɒntest", 6},
    {"the Great Wall", "长城", "", 6},
    {"national", "国家的", "'næʃ(ə)n(ə)l", 6},
    {"National Day", "国庆日", "ˈnæʃənəl de", 6},
    {"American", "美国的", "əˈmerɪkən", 6},
    {"Thanksgiving", "感恩节", "", 6},
    {"Christmas", "圣诞节", "ˈkrɪsməs", 6},
    {"holiday", "节日", "'hɒlɪdeɪ; -dɪ", 6},
    {"game", "游戏", "geɪm", 6},
    {"roll", "滚动", "rəʊl", 6},
    {"look for", "寻找", "", 6},
    {"chocolate", "巧克力", "'tʃɒk(ə)lət", 6},
    {"bunny", "兔子", "'bʌnɪ", 6},
    {"RSVP", "请赐复", "", 6},
    {"by", "在……之前", "baɪ", 6},
    {"first", "第一", "fɜːst", 6},
    {"second", "第二", "'sek(ə)nd", 6},
    {"third", "第三", "θɜːd", 6},
    {"fourth", "第四", "fɔːθ", 6},
    {"fifth", "第五", "fɪfθ", 6},
    {"twelfth", "第十二", "twelfθ", 6},
    {"twentieth", "第二十", "ˈtwentɪəθ", 6},
    {"twenty-first", "第二十一", "'twenti'fə:st", 6},
    {"twenty-third", "第二十三", "", 6},
    {"thirtieth", "第三十", "'θɜːtɪɪθ", 6},
    {"special", "特殊的", "'speʃ(ə)l", 6},
    {"fool", "蠢人", "fuːl", 6},
    {"kitten", "小猫", "'kɪt(ə)n", 6},
    {"diary", "日记", "'daɪərɪ", 6},
    {"still", "仍然", "stɪl", 6},
    {"noise", "噪音", "nɔɪz", 6},
    {"fur", "动物皮毛", "fɜː", 6},
    {"open", "开着的", "'əʊp(ə)n", 6},
    {"walk", "行走", "wɔːk", 6},
    {"hers", "她的", "hɜːz", 6},
    {"theirs", "他们的", "ðeəz", 6},
    {"ours", "我们的", "aʊəz", 6},
    {"climbing", "攀登(ing形式)", "'klaɪmɪŋ", 6},
    {"eating", "吃(ing形式)", "'iːtɪŋ", 6},
    {"playing", "玩(ing形式)", "'pleɪŋ", 6},
    {"jumping", "跳(ing形式)", "'dʒʌmpɪŋ", 6},
    {"drinking", "喝(ing形式)", "'drɪŋkɪŋ", 6},
    {"sleeping", "睡觉(ing形式)", "'sliːpɪŋ", 6},
    {"each", "每个", "iːtʃ", 6},
    {"other", "其他", "'ʌðə", 6},
    {"each other", "相互", "", 6},
    {"excited", "兴奋的", "ɪk'saɪtɪd", 6},
    {"like", "像……那样", "laɪk", 6},
    {"doing morning exercises", "做早操", "", 6},
    {"having...class", "上……课", "", 6},
    {"eating lunch", "吃午饭", "", 6},
    {"reading a book", "看书", "", 6},
    {"listening to music", "听音乐", "", 6},
    {"keep", "保持", "kiːp", 6},
    {"keep to the right", "靠右", "", 6},
    {"keep your desk clean", "保持课桌干净", "", 6},
    {"talk quietly", "小声讲话", "", 6},
    {"turn", "轮流", "tɜːn", 6},
    {"take turns", "按顺序来", "", 6},
    {"bamboo", "竹子", "bæm'buː", 6},
    {"its", "它的", "ɪts", 6},
    {"show", "展示", "ʃəʊ", 6},
    {"anything", "任何事物", "'enɪθɪŋ", 6},
    {"else", "另外", "els", 6},
    {"exhibition", "展览", "ˌeksɪˈbɪʃn", 6},
    {"say", "说", "seɪ", 6},
    {"have a look", "看一看", "", 6},
    {"sushi", "寿司", "'suːʃɪ", 6},
    {"teach", "教", "tiːtʃ", 6},
    {"sure", "当然", "ʃɔ:(r)", 6},
    {"Canadian", "加拿大的", "kə'neɪdɪən", 6},
    {"Spanish", "西班牙的", "'spænɪʃ", 6},
    {"science", "科学", "'saɪəns", 7},
    {"museum", "博物馆", "mjuː'zɪəm", 7},
    {"post office", "邮局", "ˈpəust ɔfis", 7},
    {"bookstore", "书店", "'bʊkstɔː", 7},
    {"cinema", "电影院", "ˈsɪnəmɑ:ˈsɪnəmə", 7},
    {"hospital", "医院", "'hɒspɪt(ə)l", 7},
    {"crossing", "十字路口", "'krɒsɪŋ", 7},
    {"left", "左", "left", 7},
    {"on foot", "步行", "", 7},
    {"bus", "公共汽车", "bʌs", 7},
    {"plane", "飞机", "pleɪn", 7},
    {"taxi", "出租汽车", "'tæksɪ", 7},
    {"ship", "船", "ʃɪp", 7},
    {"subway", "地铁", "'sʌbweɪ", 7},
    {"train", "火车", "treɪn", 7},
    {"slow", "慢的", "sləʊ", 7},
    {"down", "向下", "daʊn", 7},
    {"slow down", "慢下来", "", 7},
    {"stop", "停下", "stɒp", 7},
    {"Mrs", "夫人", "ˈmɪsɪz", 7},
    {"early", "早到的", "'ɜːlɪ", 7},
    {"helmet", "头盔", "'helmɪt", 7},
    {"must", "必须", "mʌst", 7},
    {"wear", "穿，戴", "weə", 7},
    {"attention", "注意", "ə'tenʃ(ə)n", 7},
    {"pay attention to", "注意", "", 7},
    {"traffic", "交通", "'træfɪk", 7},
    {"traffic lights", "交通信号灯", "", 7},
    {"Munich", "慕尼黑", "'mju:nik", 7},
    {"Germany", "德国", "'dʒɜːmənɪ", 7},
    {"Alaska", "阿拉斯加州", "ə'læskə", 7},
    {"sled", "雪橇", "sled", 7},
    {"fast", "快的", "fɑːst", 7},
    {"ferry", "轮渡", "'ferɪ", 7},
    {"Papa Westray", "帕帕韦斯特雷岛", "", 7},
    {"Scotland", "苏格兰", "'skɔtlənd", 7},
    {"visit", "拜访", "'vɪzɪt", 7},
    {"film", "电影", "fɪlm", 7},
    {"see a film", "看电影", "", 7},
    {"take a trip", "去旅行", "", 7},
    {"supermarket", "超市", "'suːpəmɑːkɪt; 'sjuː-", 7},
    {"evening", "晚上", "'iːv(ə)nɪŋ", 7},
    {"tonight", "今晚", "tə'naɪt", 7},
    {"tomorrow", "明天", "tə'mɒrəʊ", 7},
    {"next week", "下周", "nekst wi:k", 7},
    {"dictionary", "词典", "'dɪkʃ(ə)n(ə)rɪ", 7},
    {"comic", "滑稽的", "'kɒmɪk", 7},
    {"comic book", "连环画", "", 7},
    {"word", "单词", "wɜːd", 7},
    {"word book", "单词书", "'wɜːdbʊk", 7},
    {"post card", "明信片", "", 7},
    {"lesson", "课", "'les(ə)n", 7},
    {"space", "太空", "speɪs", 7},
    {"travel", "旅行", "'træv(ə)l", 7},
    {"half", "一半", "hɑːf", 7},
    {"price", "价格", "praɪs", 7},
    {"Mid-Autumn Festival", "中秋节", "", 7},
    {"together", "一起", "tə'geðə", 7},
    {"get together", "聚会", "", 7},
    {"mooncake", "月饼", "'mu:nkeɪk", 7},
    {"poem", "诗", "'pəʊɪm", 7},
    {"moon", "月亮", "muːn", 7},
    {"studies", "学习", "'stʌdiz", 7},
    {"puzzle", "谜", "'pʌz(ə)l", 7},
    {"hiking", "远足", "'haɪkɪŋ", 7},
    {"pen pal", "笔友", "", 7},
    {"hobby", "业余爱好", "'hɒbɪ", 7},
    {"jasmine", "茉莉", "'dʒæzmɪn; 'dʒæs-", 7},
    {"idea", "主意", "aɪ'dɪə", 7},
    {"Canberra", "堪培拉", "'kænbərə", 7},
    {"amazing", "令人惊奇的", "ə'meɪzɪŋ", 7},
    {"shall", "表示征求意见", "ʃæl; ʃ(ə)l", 7},
    {"goal", "射门", "gəʊl", 7},
    {"join", "加入", "dʒɒɪn", 7},
    {"club", "俱乐部", "klʌb", 7},
    {"share", "分享", "ʃeə", 7},
    {"factory", "工厂", "'fækt(ə)rɪ", 7},
    {"worker", "工人", "'wɜːkə", 7},
    {"postman", "邮递员", "'pəʊs(t)mən", 7},
    {"businessman", "商人", "'bɪznɪsmən", 7},
    {"police officer", "警察", "pəˈlis ˈɔfɪsɚ", 7},
    {"fisherman", "渔民", "'fɪʃəmən", 7},
    {"scientist", "科学家", "'saɪəntɪst", 7},
    {"pilot", "飞行员", "'paɪlət", 7},
    {"coach", "教练", "kəʊtʃ", 7},
    {"country", "国家", "'kʌntrɪ", 7},
    {"head teacher", "校长", "", 7},
    {"sea", "大海", "siː", 7},
    {"stay", "停留", "steɪ", 7},
    {"university", "大学", "juːnɪ'vɜːsɪtɪ", 7},
    {"gym", "体育馆", "dʒɪm", 7},
    {"if", "如果", "ɪf", 7},
    {"reporter", "记者", "rɪ'pɔːtə", 7},
    {"use", "使用", "juːz", 7},
    {"type", "打字", "taɪp", 7},
    {"quickly", "迅速地", "'kwɪklɪ", 7},
    {"secretary", "秘书", "ˈsekrətrɪ", 7},
    {"angry", "生气的", "'æŋgrɪ", 7},
    {"afraid", "害怕", "ə'freɪd", 7},
    {"sad", "难过的", "sæd", 7},
    {"worried", "担心的", "'wʌrɪd", 7},
    {"happy", "高兴的", "'hæpɪ", 7},
    {"see a doctor", "看病", "", 7},
    {"deep", "深的", "diːp", 7},
    {"breath", "呼吸", "breθ", 7},
    {"take a deep breath", "深呼吸", "", 7},
    {"count", "数数", "kaʊnt", 7},
    {"count to ten", "数到十", "", 7},
    {"chase", "追赶", "tʃeɪs", 7},
    {"mice", "老鼠(复数)", "maɪs", 7},
    {"bad", "坏的", "bæd", 7},
    {"hurt", "受伤", "hɜːt", 7},
    {"ill", "有病", "ɪl", 7},
    {"wrong", "错误的", "rɒŋ", 7},
    {"feel", "觉得", "fiːl", 7},
    {"well", "健康", "wel", 7},
    {"sit", "坐", "sɪt", 7},
    {"grass", "草坪", "grɑːs", 7},
    {"ant", "蚂蚁", "ænt", 7},
    {"worry", "担心", "'wʌrɪ", 7},
    {"stuck", "陷住", "stʌk", 7},
    {"mud", "泥", "mʌd", 7},
    {"pull", "拉", "pʊl", 7},
    {"everyone", "每人", "'evrɪwʌn", 7},
    {"younger", "更年轻的", "'jʌŋɡə", 8},
    {"older", "更年长的", "'əʊldə", 8},
    {"taller", "更高的", "'tɔ:lə(r)", 8},
    {"shorter", "更矮的", "", 8},
    {"longer", "更长的", "'lɒŋɡə", 8},
    {"thinner", "更瘦的", "'θɪnə", 8},
    {"heavier", "更重的", "'hevɪə", 8},
    {"bigger", "更大的", "bɪgə(r)", 8},
    {"smaller", "更小的", "smɔ:lə(r)", 8},
    {"stronger", "更强壮的", "strɒŋgə(r)", 8},
    {"dinosaur", "恐龙", "'daɪnəsɔː", 8},
    {"hall", "大厅", "hɔːl", 8},
    {"metre", "米", "'mi:tə(r)", 8},
    {"meter", "米", "ˈmi:tə(r)", 8},
    {"than", "比", "ðæn; ð(ə)n", 8},
    {"both", "两个都", "bəʊθ", 8},
    {"kilogram", "千克", "ˈkɪləɡræm", 8},
    {"countryside", "乡村", "'kʌntrɪsaɪd", 8},
    {"lower", "更低地", "'ləʊə", 8},
    {"shadow", "影子", "'ʃædəʊ", 8},
    {"smarter", "更聪明的", "'smɑ:tə", 8},
    {"become", "变成", "bɪ'kʌm", 8},
    {"cleaned", "打扫（clean 的过去式）", "kliːnd", 8},
    {"stayed", "停留（stay 的过去式）", "", 8},
    {"washed", "洗（wash 的过去式）", "wɔʃt", 8},
    {"watched", "看（watch 的过去式）", "wɒtʃ", 8},
    {"had", "有（have 的过去式）", "hæd", 8},
    {"had a cold", "感冒", "", 8},
    {"slept", "睡觉（sleep 的过去式）", "slept", 8},
    {"saw", "看见（see 的过去式）", "sɔː", 8},
    {"yesterday", "昨天", "ˈjestədɪ;-deɪ", 8},
    {"before", "在……之前", "bɪ'fɔː", 8},
    {"drank", "喝（drink 的过去式）", "dræŋk", 8},
    {"magazine", "杂志", "mægə'ziːn", 8},
    {"better", "更好的", "'betə", 8},
    {"faster", "更快的", "fɑ:stə(r)", 8},
    {"hotel", "旅馆", "həʊˈtel", 8},
    {"fixed", "修理（fix 的过去式）", "fɪkst", 8},
    {"broken", "破损的", "'brəʊk(ə)n", 8},
    {"lamp", "台灯", "læmp", 8},
    {"loud", "大声的", "laʊd", 8},
    {"enjoy", "享受……的乐趣", "ɪnˈdʒɔɪ", 8},
    {"went", "去（go 的过去式）", "went", 8},
    {"camp", "野营", "kæmp", 8},
    {"went camping", "去野营", "", 8},
    {"went fishing", "去钓鱼", "", 8},
    {"rode", "骑（ride 的过去式）", "rəʊd", 8},
    {"ate", "吃（eat 的过去式）", "et; eit", 8},
    {"took", "拿（take 的过去式）", "tʊk", 8},
    {"took pictures", "照相", "", 8},
    {"bought", "买（buy 的过去式）", "bɔːt", 8},
    {"gift", "礼物", "gɪft", 8},
    {"fell", "摔倒（fall 的过去式）", "fel", 8},
    {"off", "离开", "ɒf", 8},
    {"Labour Day", "劳动节", "", 8},
    {"mule", "骡子", "mjuːl", 8},
    {"Turpan", "吐鲁番", "", 8},
    {"could", "能", "kəd; kʊd", 8},
    {"till", "直到", "tɪl", 8},
    {"beach", "沙滩", "biːtʃ", 8},
    {"basket", "篮子", "'bɑːskɪt", 8},
    {"part", "角色", "pɑːt", 8},
    {"licked", "舔（lick 的过去式）", "lɪk", 8},
    {"laughed", "笑（laugh 的过去式）", "", 8},
    {"dining hall", "饭厅", "", 8},
    {"ago", "以前", "ə'gəʊ", 8},
    {"cycling", "骑自行车运动", "'saɪklɪŋ", 8},
    {"go cycling", "去骑自行车", "", 8},
    {"ice-skate", "滑冰", "'aisskeit", 8},
    {"badminton", "羽毛球运动", "'bædmɪnt(ə)n", 8},
    {"star", "星", "stɑː", 8},
    {"easy", "容易的", "'iːzɪ", 8},
    {"look up", "查阅", "", 8},
    {"Internet", "互联网", "'ɪntənet", 8},
    {"different", "不同的", "ˈdɪfrənt", 8},
    {"active", "活跃的", "'æktɪv", 8},
    {"race", "赛跑", "reɪs", 8},
    {"nothing", "没有什么", "'nʌθɪŋ", 8},
    {"thought", "想（think 的过去式）", "θɔːt", 8},
    {"felt", "感觉（feel 的过去式）", "felt", 8},
    {"cheetah", "猎豹", "'tʃiːtə", 8},
    {"woke", "醒（wake 的过去式）", "wəʊk", 8},
    {"dream", "梦", "driːm", 8},
    {"straight", "笔直的", "streɪt", 8},
    {"ask", "问", "ɑːsk", 8},
    {"sir", "先生", "sɜː", 8},
    {"interesting", "有趣的", "ˈɪntrəstɪŋ", 8},
    {"Italian", "意大利的", "ɪˈtælɪən", 8},
    {"restaurant", "餐馆", "ˈrestrɒnt", 8},
    {"pizza", "比萨饼", "'piːtsə; 'pɪtsə", 8},
    {"street", "大街", "striːt", 8},
    {"get", "到达", "get", 8},
    {"GPS", "全球定位系统", "", 8},
    {"gave", "给（give 的过去式）", "ɡeɪv", 8},
    {"feature", "特点", "'fiːtʃə", 8},
    {"follow", "跟着", "'fɒləʊ", 8},
    {"far", "较远的", "fɑː", 8},
    {"tell", "告诉", "tel", 8},
};

#endif