/**
 * @file word_pool.h
 * @brief 小学英语单词库（PEP 人教版 3-6 年级，819 词）
 *
 * 用于"训练 = 学英语单词"反向学习机制：
 * 玩家以为在训练宠物，实际在做英语单词选词题。
 */
#ifndef WORD_POOL_H
#define WORD_POOL_H

#include <stdint.h>

typedef struct {
    const char *en;  /* 英文单词 */
    const char *cn;  /* 中文释义 */
} word_entry_t;

static const word_entry_t word_pool[] = {
    {"a few", "一些"},
    {"a.m.", "上午"},
    {"above", "在⋯⋯上面"},
    {"active", "活跃的"},
    {"afraid", "害怕"},
    {"after", "在⋯⋯之后"},
    {"ago", "以前"},
    {"Alaska", "阿拉斯加州"},
    {"all", "完全"},
    {"also", "还"},
    {"always", "总是"},
    {"amazing", "令人惊奇的"},
    {"American", "美国的"},
    {"and", "和"},
    {"angry", "生气的"},
    {"animal", "动物"},
    {"ant", "蚂蚁"},
    {"any", "任何的"},
    {"anything", "任何事物"},
    {"apple", "苹果"},
    {"April", "四月"},
    {"aren't", "不是（= are not）"},
    {"arm", "胳膊"},
    {"art room", "美术教室"},
    {"ask", "问"},
    {"at", "（接邮件地址）"},
    {"ate", "吃"},
    {"attention", "注意"},
    {"August", "八月"},
    {"aunt", "阿姨"},
    {"autumn", "秋天"},
    {"baby brother", "小弟弟"},
    {"bad", "邪恶的"},
    {"badminton", "羽毛球运动"},
    {"bag", "包"},
    {"ball", "球"},
    {"bamboo", "竹子"},
    {"banana", "香蕉"},
    {"basket", "篮子"},
    {"basketball", "篮球"},
    {"bathroom", "浴室"},
    {"be careful", "小心"},
    {"beach", "沙滩"},
    {"bear", "熊"},
    {"beautiful", "美丽的"},
    {"because", "因为"},
    {"become", "变成"},
    {"bed", "床"},
    {"bedroom", "卧室"},
    {"beef", "牛肉"},
    {"before", "在⋯⋯之前"},
    {"behind", "在⋯⋯后面"},
    {"beside", "在旁边"},
    {"best", "最"},
    {"better", "更好的"},
    {"between", "在⋯⋯中间"},
    {"big", "大的"},
    {"bigger", "更大的"},
    {"bike", "自行车"},
    {"bird", "鸟"},
    {"black", "黑色；黑色的"},
    {"blackboard", "黑板"},
    {"blue", "蓝色；蓝色的"},
    {"boat", "小船"},
    {"boating", "划船"},
    {"body", "身体"},
    {"book", "书"},
    {"bookstore", "书店"},
    {"both", "两个都"},
    {"bottle", "瓶子"},
    {"bought", "买"},
    {"bowl", "碗"},
    {"box", "盒；箱"},
    {"boy", "男孩, 儿子, 孩子气的人, 男仆"},
    {"bread", "面包"},
    {"breakfast", "早餐"},
    {"breath", "呼吸"},
    {"bridge", "桥"},
    {"broken", "破损的"},
    {"brother", "兄；弟"},
    {"brown", "棕色；棕色的"},
    {"building", "建筑"},
    {"bunny", "兔子"},
    {"bus", "公共汽车"},
    {"businessman", "商人"},
    {"busy", "忙的"},
    {"but", "但是"},
    {"buy", "买"},
    {"by", "在⋯⋯之前"},
    {"cake", "蛋糕"},
    {"camp", "野营"},
    {"Canada", "加拿大"},
    {"Canadian", "加拿大的"},
    {"Canberra", "堪培拉"},
    {"candy", "糖果"},
    {"cap", "帽子"},
    {"car", "小汽车"},
    {"carrot", "胡萝卜"},
    {"cartoon", "漫画"},
    {"cat", "猫"},
    {"cave", "山洞"},
    {"chair", "椅子"},
    {"chase", "追赶"},
    {"cheap", "便宜的"},
    {"cheetah", "猎豹"},
    {"chicken", "鸡肉"},
    {"child", "儿童"},
    {"children", "儿童"},
    {"China", "中国"},
    {"Chinese book", "语文书"},
    {"chocolate", "巧克力"},
    {"chopsticks", "筷子"},
    {"Christmas", "圣诞节"},
    {"cinema", "电影院"},
    {"class", "班级"},
    {"classroom", "教室"},
    {"clean", "打扫"},
    {"clean my room", "打扫我的房间"},
    {"cleaned", "打扫"},
    {"clever", "聪明的"},
    {"climbing", "攀登"},
    {"clock", "时钟"},
    {"clothes", "服装"},
    {"cloudy", "多云的"},
    {"club", "俱乐部"},
    {"coach", "教练"},
    {"coat", "大衣"},
    {"cold", "冷的"},
    {"come on", "加油"},
    {"comic", "滑稽的"},
    {"comic book", "连环画"},
    {"computer", "计算机"},
    {"computer room", "计算机房"},
    {"contest", "比赛"},
    {"cook", "厨师"},
    {"cooking", "烹饪"},
    {"cool", "凉的"},
    {"could", "能"},
    {"count", "数数"},
    {"count to ten", "数到十"},
    {"country", "国家"},
    {"countryside", "乡村"},
    {"cousin", "同辈表亲"},
    {"cow", "牛"},
    {"crayon", "蜡笔"},
    {"crossing", "十字路口"},
    {"cute", "可爱的"},
    {"cycling", "骑自行车运动"},
    {"dad", "（口语）爸爸；爹爹"},
    {"dance", "跳舞"},
    {"dancing", "跳舞"},
    {"day", "一天"},
    {"Dear", "亲爱的"},
    {"December", "十二月"},
    {"deep", "深的"},
    {"degree", "度"},
    {"delicious", "美味的"},
    {"desk", "书桌"},
    {"diary", "日记"},
    {"dictionary", "词典"},
    {"different", "不同的"},
    {"dining hall", "饭厅"},
    {"dinner", "正餐"},
    {"dinosaur", "恐龙"},
    {"dirty", "肮脏的"},
    {"do", "做"},
    {"do homework", "做作业"},
    {"do kung fu", "练武术"},
    {"do morning exercise", "做早操"},
    {"doctor", "医生"},
    {"dog", "狗"},
    {"doing morning exercises", "做早操"},
    {"dollar", "元"},
    {"door", "门"},
    {"down", "减少"},
    {"drank", "喝"},
    {"draw", "画"},
    {"draw cartoons", "画漫画"},
    {"dream", "梦"},
    {"dress", "连衣裙"},
    {"drink", "喝"},
    {"drinking", "喝"},
    {"driver", "司机"},
    {"duck", "鸭子"},
    {"each", "每个"},
    {"each other", "相互"},
    {"ear", "耳朵"},
    {"early", "早到的"},
    {"Easter", "复活节"},
    {"easy", "容易的"},
    {"eat", "吃"},
    {"eat breakfast", "吃早饭"},
    {"eat dinner", "吃晚饭"},
    {"eating", "吃"},
    {"eating lunch", "吃午饭"},
    {"egg", "蛋"},
    {"eight", "八"},
    {"eighteen", "十八"},
    {"eighty", "八十"},
    {"elephant", "大象"},
    {"eleven", "十一"},
    {"else", "另外"},
    {"email", "电子邮件"},
    {"English book", "英语书"},
    {"English class", "英语课"},
    {"enjoy", "享受⋯⋯的乐趣"},
    {"eraser", "橡皮"},
    {"evening", "晚上"},
    {"every", "每一个"},
    {"everyone", "每人"},
    {"everywhere", "处处"},
    {"excited", "兴奋地"},
    {"exercise", "活动"},
    {"exhibition", "展览"},
    {"expensive", "贵的"},
    {"eye", "眼睛"},
    {"face", "脸"},
    {"factory", "工厂"},
    {"fall", "落下"},
    {"family", "家；家庭"},
    {"fan", "风扇"},
    {"far", "较远的"},
    {"farm", "农场"},
    {"farmer", "农民"},
    {"fast", "快的"},
    {"faster", "更快的"},
    {"fat", "胖的；肥的"},
    {"father", "父亲；爸爸"},
    {"favourite", "特别喜欢的"},
    {"feature", "特点"},
    {"February", "二月"},
    {"feel", "觉得"},
    {"fell", "摔倒"},
    {"felt", "感觉"},
    {"ferry", "轮渡"},
    {"few", "不多"},
    {"fifteen", "十五"},
    {"fifth", "第五"},
    {"film", "电影"},
    {"find", "找到"},
    {"finish", "完成"},
    {"first", "第一"},
    {"first floor", "一楼（美）；二楼（英）"},
    {"fish", "钓鱼"},
    {"fisherman", "渔民"},
    {"five", "五"},
    {"fixed", "修理"},
    {"floor", "地板"},
    {"flower", "花"},
    {"fly", "放（风筝）"},
    {"follow", "跟着"},
    {"food", "食物"},
    {"fool", "蠢人"},
    {"foot", "脚"},
    {"football player", "足球运动员"},
    {"forest", "森林"},
    {"fork", "餐叉"},
    {"forty", "四十"},
    {"four", "四"},
    {"fourteen", "十四"},
    {"fourth", "第四"},
    {"fresh", "新鲜的"},
    {"Friday", "星期五"},
    {"fridge", "冰箱"},
    {"friend", "朋友，友人；支持者，同情者"},
    {"friendly", "友好的"},
    {"front", "正面"},
    {"fruit", "水果"},
    {"funny", "滑稽的；好笑的"},
    {"fur", "动物皮毛"},
    {"game", "游戏"},
    {"garden", "花园"},
    {"gave", "提供"},
    {"Germany", "德国"},
    {"get", "到达"},
    {"get together", "聚会"},
    {"get up", "起床"},
    {"gift", "礼物"},
    {"giraffe", "长颈鹿"},
    {"girl", "女孩, 少女, 女仆, (商店等的)女工作人员"},
    {"glasses", "眼镜"},
    {"glove", "手套"},
    {"go boating", "去划船"},
    {"go cycling", "去骑自行车"},
    {"go for a walk", "散步"},
    {"go home", "回家"},
    {"go on a picnic", "去野餐"},
    {"go shopping", "购物"},
    {"go swimming", "去游泳"},
    {"go swimming.", "去游泳"},
    {"go to bed", "去睡觉"},
    {"go to school", "上学"},
    {"goal", "射门"},
    {"goat", "山羊"},
    {"good job", "做得好"},
    {"GPS", "全球（卫星）"},
    {"grandfather", "（外）祖父"},
    {"grandma", "（口语）（外）祖母"},
    {"grandmother", "（外）祖母"},
    {"grandpa", "（口语）（外）祖父"},
    {"grandparent", "（外）祖父母"},
    {"grape", "葡萄"},
    {"grass", "草坪"},
    {"green", "绿色；绿色的"},
    {"green beans", "豆角"},
    {"gym", "体育馆"},
    {"had", "得病（例如 had a cold 得了感冒）"},
    {"had a cold", "感冒"},
    {"hair", "头发"},
    {"half", "一半"},
    {"hall", "大厅"},
    {"hamburger", "汉堡包"},
    {"hand", "手"},
    {"happy", "高兴的"},
    {"hard-working", "努力的"},
    {"hat", "帽子"},
    {"have a look", "看一看"},
    {"have...class", "上⋯⋯课"},
    {"having...class", "上⋯⋯课"},
    {"he", "他；它（指雄性动物）"},
    {"head", "头"},
    {"head teacher", "校长"},
    {"healthy", "健康的"},
    {"heavier", "更重的"},
    {"helmet", "头盔"},
    {"help", "帮助"},
    {"help yourself", "为（自己）取用"},
    {"helpful", "有用的"},
    {"hen", "母鸡"},
    {"her", "她的"},
    {"hers", "她的"},
    {"high", "高的"},
    {"hiking", "远足"},
    {"hill", "小山"},
    {"him", "他"},
    {"his", "他的"},
    {"hobby", "业余爱好"},
    {"holiday", "节日"},
    {"homework", "作业"},
    {"horse", "马"},
    {"hospital", "医院"},
    {"hot", "热的"},
    {"hotel", "旅馆"},
    {"house", "房子"},
    {"house.", "房屋"},
    {"how about...", "怎么样？"},
    {"how much", "多少钱"},
    {"hurry up", "快点"},
    {"hurt", "受伤"},
    {"ice cream", "冰淇淋"},
    {"ice-skate", "滑冰"},
    {"idea", "主意"},
    {"if", "如果"},
    {"ill", "有病"},
    {"in", "在⋯⋯里"},
    {"in front of", "在⋯⋯前面"},
    {"interesting", "有趣的"},
    {"Internet", "互联网"},
    {"island", "岛"},
    {"Italian", "意大利的"},
    {"its", "它的"},
    {"jacket", "夹克衫"},
    {"January", "一月"},
    {"jasmine", "茉莉"},
    {"job", "工作"},
    {"join", "加入"},
    {"juice", "果汁"},
    {"July", "七月"},
    {"jumping", "跳"},
    {"June", "六月"},
    {"just", "正好"},
    {"just a minute", "稍等一会儿"},
    {"keep", "保持"},
    {"keep to the right", "靠右"},
    {"keep your desk clean", "保持课桌干净"},
    {"key", "钥匙"},
    {"kid", "小孩"},
    {"kilogram", "千克"},
    {"kind", "体贴的"},
    {"kitchen", "厨房"},
    {"kite", "风筝"},
    {"kitten", "小猫"},
    {"knife", "刀"},
    {"know", "知道"},
    {"kung fu", "功夫"},
    {"Labour Day", "劳动节"},
    {"lake", "湖"},
    {"lamp", "台灯"},
    {"last", "最近"},
    {"late", "晚"},
    {"laughed", "笑"},
    {"leaf", "叶子"},
    {"learn", "学习"},
    {"left", "左"},
    {"leg", "腿"},
    {"lesson", "课"},
    {"letter", "信"},
    {"library", "图书馆"},
    {"licked", "舔"},
    {"light", "电灯"},
    {"like", "像⋯⋯那样"},
    {"listening to music", "听音乐"},
    {"little", "小的"},
    {"live", "居住"},
    {"living room", "客厅"},
    {"London", "伦敦"},
    {"long", "长的"},
    {"longer", "更长的"},
    {"look for", "寻找"},
    {"look up", "查阅"},
    {"lost", "丢失"},
    {"lot", "大量"},
    {"lots of", "大量"},
    {"loud", "大声的"},
    {"love", "爱你的"},
    {"lovely", "可爱的"},
    {"lower", "更低地"},
    {"lunch", "午饭"},
    {"magazine", "杂志"},
    {"make a snowman", "堆雪人"},
    {"man", "男人"},
    {"map", "地图"},
    {"March", "三月"},
    {"maths book", "数学书"},
    {"May", "五月"},
    {"meet", "集会"},
    {"meter", "米"},
    {"metre", "米"},
    {"mice", "老鼠"},
    {"Mid-Autumn Festival", "中秋节"},
    {"milk", "牛奶"},
    {"mine", "我的"},
    {"Monday", "星期一"},
    {"monkey", "猴子"},
    {"moon", "月亮"},
    {"mooncake", "月饼"},
    {"more", "更多的"},
    {"Moscow", "莫斯科"},
    {"mother", "母亲；妈妈"},
    {"mountain", "山"},
    {"mouse", "老鼠"},
    {"mouth", "嘴"},
    {"move", "搬家"},
    {"Mrs", "夫人"},
    {"Ms", "女士"},
    {"mud", "泥"},
    {"mule", "骡子"},
    {"mum", "妈妈"},
    {"Munich", "慕尼黑"},
    {"museum", "博物馆"},
    {"music class", "音乐课"},
    {"music room", "音乐教室"},
    {"must", "必须"},
    {"national", "国家的"},
    {"National Day", "国庆日"},
    {"nature", "自然界"},
    {"near", "距离近"},
    {"need", "需要"},
    {"new", "新的，新近的；新来的；不熟悉的"},
    {"New York", "纽约"},
    {"next", "下一个的"},
    {"next to", "紧邻"},
    {"next week", "下周"},
    {"nice", "好的"},
    {"nine", "九"},
    {"nineteen", "十九"},
    {"no", "不"},
    {"no problem", "没问题"},
    {"noise", "噪音"},
    {"noodles", "面条"},
    {"nose", "鼻子"},
    {"notebook", "笔记本"},
    {"nothing", "没有什么"},
    {"November", "十一月"},
    {"now", "现在"},
    {"nurse", "护士"},
    {"o'clock", "⋯⋯点钟"},
    {"October", "十月"},
    {"of course", "当然"},
    {"off", "落下"},
    {"often", "时常"},
    {"OK", "好；行"},
    {"old", "老的"},
    {"older", "更年长的"},
    {"on", "在⋯⋯上"},
    {"on foot", "步行"},
    {"one", "一"},
    {"onion", "洋葱"},
    {"open", "开着的"},
    {"or", "或者"},
    {"orange", "橙色；橙色的"},
    {"other", "其他"},
    {"our", "我们的"},
    {"ours", "我们的"},
    {"outside", "在户外"},
    {"over", "结束"},
    {"p.m.", "下午"},
    {"pack", "收拾"},
    {"paint", "绘画"},
    {"panda", "大熊猫"},
    {"pants", "裤子"},
    {"Papa Westray", "帕帕韦斯特雷岛"},
    {"parents", "父母"},
    {"park", "公园"},
    {"part", "角色"},
    {"party", "聚会"},
    {"pass", "给"},
    {"pay attention to", "注意"},
    {"PE class", "体育课"},
    {"pear", "梨"},
    {"pen", "钢笔"},
    {"pen pal", "笔友"},
    {"pencil", "铅笔"},
    {"pencil box", "铅笔盒"},
    {"people", "人们"},
    {"phone", "电话"},
    {"photo", "照片"},
    {"pick", "摘"},
    {"pick apples", "摘苹果"},
    {"picnic", "野餐"},
    {"picture", "图画"},
    {"pig", "猪"},
    {"pilot", "飞行员"},
    {"ping-pong", "乒乓球"},
    {"pink", "粉色"},
    {"pizza", "比萨饼"},
    {"plane", "飞机"},
    {"plant", "种植"},
    {"plate", "盘子"},
    {"play", "戏剧"},
    {"play basketball", "打篮球"},
    {"play football", "踢足球"},
    {"play ping-pong", "打乒乓球"},
    {"play sports", "进行体育运动"},
    {"play the pipa", "弹琵琶"},
    {"playground", "操场"},
    {"playing", "玩"},
    {"poem", "诗"},
    {"police officer", "警察"},
    {"polite", "有礼貌的"},
    {"post card", "明信片"},
    {"post office", "邮局"},
    {"postman", "邮递员"},
    {"potato", "马铃薯"},
    {"pretty", "美丽的"},
    {"price", "价格"},
    {"problem", "没问题"},
    {"pull", "拉"},
    {"pupil", "小学生"},
    {"puppy", "小狗"},
    {"puzzle", "谜"},
    {"quickly", "迅速地"},
    {"quiet", "安静的"},
    {"rabbit", "兔"},
    {"race", "赛跑"},
    {"rainy", "阴雨的"},
    {"read", "读"},
    {"read books", "看书"},
    {"reading a book", "看书"},
    {"ready", "准备好"},
    {"really", "真的"},
    {"red", "红色；红色的"},
    {"reporter", "记者"},
    {"restaurant", "餐馆"},
    {"rice", "米饭"},
    {"right", "右"},
    {"river", "河"},
    {"robot", "机器人"},
    {"rode", "骑"},
    {"roll", "滚动"},
    {"RSVP", "请赐复"},
    {"ruler", "尺子"},
    {"sad", "难过的"},
    {"salad", "沙拉"},
    {"sale", "特价销售"},
    {"sandwich", "三明治"},
    {"Saturday", "星期六"},
    {"saw", "看"},
    {"say", "说；讲"},
    {"scarf", "围巾"},
    {"schedule", "工作计划"},
    {"school", "学校"},
    {"schoolbag", "书包"},
    {"science", "科学"},
    {"scientist", "科学家"},
    {"Scotland", "苏格兰"},
    {"sea", "大海"},
    {"season", "季节"},
    {"second", "第二"},
    {"second floor", "二楼"},
    {"secretary", "秘书"},
    {"see a doctor", "看病"},
    {"see a film", "看电影"},
    {"send", "邮寄"},
    {"September", "九月"},
    {"seven", "七"},
    {"seventeen", "十七"},
    {"shadow", "影子"},
    {"shall", "表示征求意见"},
    {"share", "分享"},
    {"she", "她；（指雌性动物）它"},
    {"sheep", "绵羊"},
    {"ship", "船"},
    {"shirt", "衬衫"},
    {"shoe", "鞋"},
    {"shop", "购物"},
    {"short", "矮的；短的"},
    {"shorter", "更矮的"},
    {"shorts", "短裤"},
    {"should", "应该"},
    {"show", "演出"},
    {"shy", "羞怯的"},
    {"sing", "唱"},
    {"sing English songs", "唱英文歌曲"},
    {"Singapore", "新加坡城"},
    {"sir", "先生"},
    {"sister", "姐；妹"},
    {"sit", "坐"},
    {"six", "六"},
    {"sixteen", "十六"},
    {"size", "尺码"},
    {"skirt", "女裙"},
    {"sled", "雪橇"},
    {"sleeping", "睡觉"},
    {"slept", "睡觉"},
    {"slow", "慢的"},
    {"slow down", "慢下来"},
    {"small", "小的"},
    {"smaller", "更小的"},
    {"smarter", "更聪明的"},
    {"snow", "雪"},
    {"snowman", "雪人"},
    {"snowy", "下雪的"},
    {"so", "这么；那么"},
    {"so much", "非常地"},
    {"sock", "短袜"},
    {"sofa", "长沙发"},
    {"sometimes", "有时"},
    {"song", "歌曲"},
    {"sound", "听起来好像"},
    {"soup", "汤"},
    {"space", "太空"},
    {"Spain", "西班牙"},
    {"Spanish", "西班牙的"},
    {"speak", "会说"},
    {"speak English", "说英语"},
    {"special", "特殊的"},
    {"spoon", "匙,勺子"},
    {"sport", "体育运动"},
    {"sports meet", "运动会"},
    {"spring", "春天"},
    {"star", "星"},
    {"start", "开始"},
    {"stay", "暂住"},
    {"stayed", "待"},
    {"still", "仍然"},
    {"stop", "停下"},
    {"storybook", "故事书"},
    {"straight", "笔直的"},
    {"strawberry", "草莓"},
    {"street", "大街"},
    {"strict", "严厉的"},
    {"strong", "强壮的"},
    {"stronger", "更强壮的"},
    {"stuck", "陷住"},
    {"student", "学生, 学者"},
    {"studies", "学习"},
    {"study", "书房"},
    {"subway", "地铁"},
    {"summer", "夏天"},
    {"Sunday", "星期日"},
    {"sunglasses", "太阳镜"},
    {"sunny", "阳光充足的"},
    {"supermarket", "超市"},
    {"sure", "当然"},
    {"sushi", "寿司"},
    {"sweater", "毛衣"},
    {"sweet", "甜的"},
    {"swim", "游泳"},
    {"Sydney", "悉尼"},
    {"table", "桌子"},
    {"tail", "尾巴"},
    {"take", "上（课）"},
    {"take a dancing class", "上舞蹈课"},
    {"take a deep breath", "深呼吸"},
    {"take a trip", "去旅行"},
    {"take turns", "按顺序来"},
    {"talk quietly", "小声讲话"},
    {"tall", "高的"},
    {"taller", "更高的"},
    {"taxi", "出租汽车"},
    {"tea", "茶"},
    {"teach", "教"},
    {"teacher", "教师, 老师, 导师"},
    {"teacher's desk", "讲台"},
    {"teacher's office", "教师办公室"},
    {"tell", "告诉"},
    {"ten", "十"},
    {"than", "比"},
    {"Thanksgiving", "感恩节"},
    {"the Great Wall", "长城"},
    {"their", "他们的"},
    {"theirs", "他们的"},
    {"them", "他们"},
    {"there", "（存在或发生）"},
    {"these", "这些"},
    {"thin", "瘦的"},
    {"thing", "事情"},
    {"thinner", "更瘦的"},
    {"third", "第三"},
    {"thirsty", "渴的"},
    {"thirteen", "十三"},
    {"thirtieth", "第三十"},
    {"thirty", "三十"},
    {"those", "那些"},
    {"thought", "想"},
    {"three", "三"},
    {"Thursday", "星期四"},
    {"tiger", "老虎"},
    {"till", "直到"},
    {"tired", "疲倦的"},
    {"today", "今天；现在，目前"},
    {"together", "一起"},
    {"tomato", "西红柿"},
    {"tomorrow", "明天"},
    {"tonight", "今晚"},
    {"too", "太"},
    {"took", "拍照"},
    {"took pictures", "照相"},
    {"toy", "玩具"},
    {"traffic", "交通"},
    {"traffic lights", "交通信号灯"},
    {"train", "火车"},
    {"travel", "旅行"},
    {"tree", "树"},
    {"trip", "绊倒"},
    {"try", "试"},
    {"try on", "试穿"},
    {"Tuesday", "星期二"},
    {"turn", "顺序"},
    {"Turpan", "吐鲁番"},
    {"TV", "电视"},
    {"twelfth", "第十二"},
    {"twelve", "十二"},
    {"twentieth", "第二十"},
    {"twenty", "二十"},
    {"twenty-first", "第二十一"},
    {"twenty-third", "第二十三"},
    {"two", "二"},
    {"type", "打字"},
    {"UK", "英国"},
    {"umbrella", "伞"},
    {"uncle", "叔叔"},
    {"under", "在⋯⋯下面"},
    {"university", "大学"},
    {"us", "我们"},
    {"USA", "美国"},
    {"use", "使用"},
    {"usually", "通常地"},
    {"vacation", "假期"},
    {"vegetable", "蔬菜"},
    {"village", "村庄"},
    {"visit", "拜访"},
    {"wait", "等待"},
    {"walk", "行走"},
    {"wall", "墙壁"},
    {"want", "要"},
    {"warm", "温暖的"},
    {"wash", "洗"},
    {"wash my clothes", "洗我的衣服"},
    {"washed", "洗"},
    {"watch", "看"},
    {"watch TV", "看电视"},
    {"watched", "看"},
    {"water", "水"},
    {"water bottle", "水瓶"},
    {"watermelon", "西瓜"},
    {"way", "方向"},
    {"wear", "戴"},
    {"wear.", "穿"},
    {"weather", "天气"},
    {"Wednesday", "星期三"},
    {"weekend", "周末"},
    {"well", "健康"},
    {"we'll", "我们将……（=we will）"},
    {"went", "去"},
    {"went camping", "去野营"},
    {"went fishing", "去钓鱼"},
    {"when", "什么时候"},
    {"which", "哪一个"},
    {"white", "白色；白色的"},
    {"whose", "谁的"},
    {"why", "为什么"},
    {"will", "将要"},
    {"win", "获胜"},
    {"window", "窗户"},
    {"windy", "多风的"},
    {"winter", "冬天"},
    {"woke", "醒"},
    {"woman", "女人"},
    {"wonderful", "极好的"},
    {"word", "单词"},
    {"word book", "单词书"},
    {"work", "工作"},
    {"worker", "工人"},
    {"world", "世界"},
    {"worried", "担心的"},
    {"worry", "担心"},
    {"wow", "呀"},
    {"wrong", "有毛病"},
    {"year", "年"},
    {"yellow", "黄色；黄色的"},
    {"yesterday", "昨天"},
    {"young", "年轻的"},
    {"younger", "更年轻的"},
    {"your", "你（们）的"},
    {"yours", "你的"},
    {"yum", "味道好"},
    {"zoo", "动物园"},
};

#define WORD_POOL_SIZE 819

#endif // WORD_POOL_H
