/**
 * @file word_pool.h
 * @brief PEP 人教版 3-6 年级英语词库 v12（817 词，原译不动）
 * 字段：en 英文 / cn 中文释义 / ph 音标(英音) / book 册(0=三上..7=六下)
 */
#ifndef WORD_POOL_H
#define WORD_POOL_H

#include <stdint.h>

typedef struct {
    const char *en;
    const char *cn;
    const char *ph;
    uint8_t book;
} word_entry_t;

#define WORD_POOL_SIZE 817

static const word_entry_t word_pool[] = {
    {"ruler", "尺子", "'ruːlə", 0},
    {"pencil", "铅笔", "'pens(ə)l; -sɪl", 0},
    {"eraser", "橡皮", "ɪ'reɪzə", 0},
    {"crayon", "蜡笔", "ˈkreɪən", 0},
    {"bag", "包", "bæg", 0},
    {"pen", "钢笔", "pen", 0},
    {"pencil box", "铅笔盒", "'pɛnsl bɑks", 0},
    {"book", "书", "bʊk", 0},
    {"no", "不", "nəʊ", 0},
    {"your", "你的", "jɔ:(r)", 0},
    {"red", "红色", "red", 0},
    {"green", "绿色", "griːn", 0},
    {"yellow", "黄色", "'jeləʊ", 0},
    {"blue", "蓝色", "bluː", 0},
    {"black", "黑色", "blæk", 0},
    {"brown", "棕色", "braʊn", 0},
    {"white", "白色", "waɪt", 0},
    {"orange", "橙色", "'ɒrɪn(d)ʒ", 0},
    {"OK", "好", "", 0},
    {"mum", "妈妈", "mʌm", 0},
    {"face", "脸", "feɪs", 0},
    {"ear", "耳朵", "ɪə", 0},
    {"eye", "眼睛", "aɪ", 0},
    {"nose", "鼻子", "nəʊz", 0},
    {"mouth", "嘴", "maʊθ", 0},
    {"arm", "胳膊", "ɑːm", 0},
    {"hand", "手", "hænd", 0},
    {"head", "头", "hed", 0},
    {"body", "身体", "'bɒdɪ", 0},
    {"leg", "腿", "leg", 0},
    {"foot", "脚", "fʊt", 0},
    {"school", "学校", "skuːl", 0},
    {"duck", "鸭子", "dʌk", 0},
    {"pig", "猪", "pɪg", 0},
    {"cat", "猫", "kæt", 0},
    {"bear", "熊", "beə", 0},
    {"dog", "狗", "dɒg", 0},
    {"elephant", "大象", "'elɪf(ə)nt", 0},
    {"monkey", "猴子", "'mʌŋkɪ", 0},
    {"bird", "鸟", "bɜːd", 0},
    {"tiger", "老虎", "'taɪgə", 0},
    {"panda", "大熊猫", "'pændə", 0},
    {"zoo", "动物园", "zuː", 0},
    {"funny", "滑稽的", "'fʌnɪ", 0},
    {"bread", "面包", "bred", 0},
    {"juice", "果汁", "dʒuːs", 0},
    {"egg", "蛋", "eg", 0},
    {"milk", "牛奶", "mɪlk", 0},
    {"water", "水", "'wɔːtə", 0},
    {"cake", "蛋糕", "keɪk", 0},
    {"fish", "鱼", "fɪʃ", 0},
    {"rice", "米饭", "raɪs", 0},
    {"one", "一", "wʌn", 0},
    {"two", "二", "tuː", 0},
    {"three", "三", "θriː", 0},
    {"four", "四", "fɔː", 0},
    {"five", "五", "faɪv", 0},
    {"six", "六", "sɪks", 0},
    {"seven", "七", "'sev(ə)n", 0},
    {"eight", "八", "eɪt", 0},
    {"nine", "九", "naɪn", 0},
    {"ten", "十", "ten", 0},
    {"brother", "兄", "'brʌðə", 0},
    {"plate", "盘子", "pleɪt", 0},
    {"UK", "英国", "", 1},
    {"Canada", "加拿大", "'kænədə", 1},
    {"USA", "美国", "", 1},
    {"China", "中国", "ˈtʃaɪnə", 1},
    {"she", "她", "ʃiː", 1},
    {"student", "学生", "'stjuːd(ə)nt", 1},
    {"pupil", "小学生", "'pjuːpɪl; -p(ə)l", 1},
    {"he", "他", "hiː", 1},
    {"teacher", "教师", "'tiːtʃə", 1},
    {"boy", "男孩", "bɒɪ", 1},
    {"and", "和", "ənd; (ə)n; ænd", 1},
    {"girl", "女孩", "gɜːl", 1},
    {"new", "新的，新近的", "njuː", 1},
    {"friend", "朋友，友人", "frend", 1},
    {"today", "今天", "tə'deɪ", 1},
    {"father", "父亲", "'fɑːðə", 1},
    {"dad", "爸爸", "dæd", 1},
    {"man", "男人", "mæn", 1},
    {"woman", "女人", "'wʊmən", 1},
    {"mother", "母亲", "'mʌðə", 1},
    {"sister", "姐", "'sɪstə", 1},
    {"grandmother", "祖母", "'græn(d)mʌðə", 1},
    {"grandma", "祖母", "'græn(d)mɑː", 1},
    {"grandfather", "祖父", "'græn(d)fɑːðə", 1},
    {"grandpa", "祖父", "ˈgrænpɑ:", 1},
    {"family", "家", "ˈfæməlɪ", 1},
    {"thin", "瘦的", "θɪn", 1},
    {"fat", "胖的", "fæt", 1},
    {"tall", "高的", "tɔːl", 1},
    {"short", "矮的", "ʃɔːt", 1},
    {"long", "长的", "lɒŋ", 1},
    {"small", "小的", "smɔːl", 1},
    {"big", "大的", "bɪg", 1},
    {"giraffe", "长颈鹿", "dʒɪˈrɑ:f", 1},
    {"so", "这么", "səʊ", 1},
    {"children", "儿童", "'tʃɪldrən", 1},
    {"child", "儿童", "tʃaɪld", 1},
    {"tail", "尾巴", "teɪl", 1},
    {"on", "在⋯⋯上", "ɒn", 1},
    {"in", "在⋯⋯里", "ɪn", 1},
    {"under", "在⋯⋯下面", "'ʌndə", 1},
    {"chair", "椅子", "tʃeə", 1},
    {"desk", "书桌", "desk", 1},
    {"cap", "帽子", "kæp", 1},
    {"ball", "球", "bɔːl", 1},
    {"car", "小汽车", "kɑː", 1},
    {"boat", "小船", "bəʊt", 1},
    {"map", "地图", "mæp", 1},
    {"toy", "玩具", "tɒɪ", 1},
    {"box", "盒", "bɒks", 1},
    {"pear", "梨", "peə", 1},
    {"apple", "苹果", "'æp(ə)l", 1},
    {"banana", "香蕉", "bə'nɑːnə", 1},
    {"watermelon", "西瓜", "'wɔːtəmelən", 1},
    {"strawberry", "草莓", "'strɔːb(ə)rɪ", 1},
    {"grape", "葡萄", "greɪp", 1},
    {"buy", "买", "baɪ", 1},
    {"fruit", "水果", "fruːt", 1},
    {"eleven", "十一", "ɪ'lev(ə)n", 1},
    {"twelve", "十二", "twelv", 1},
    {"thirteen", "十三", "θɜː'tiːn; 'θɜːtiːn", 1},
    {"fourteen", "十四", "fɔː'tiːn; 'fɔːtiːn", 1},
    {"fifteen", "十五", "fɪf'tiːn; 'fɪftiːn", 1},
    {"sixteen", "十六", "sɪks'tiːn; 'sɪkstiːn", 1},
    {"seventeen", "十七", "sev(ə)n'tiːn; 'sev(ə)ntiːn", 1},
    {"eighteen", "十八", "eɪ'tiːn; 'eɪtiːn", 1},
    {"nineteen", "十九", "naɪn'tiːn; 'naɪntiːn", 1},
    {"twenty", "二十", "'twentɪ", 1},
    {"kite", "风筝", "kaɪt", 1},
    {"beautiful", "美丽的", "ˈbju:tɪfl", 1},
    {"classroom", "教室", "'klɑːsruːm; -rʊm", 2},
    {"window", "窗户", "'wɪndəʊ", 2},
    {"blackboard", "黑板", "'blækbɔːd", 2},
    {"light", "电灯", "laɪt", 2},
    {"picture", "图画", "'pɪktʃə", 2},
    {"door", "门", "dɔː", 2},
    {"teacher's desk", "讲台", "", 2},
    {"computer", "计算机", "kəm'pjuːtə", 2},
    {"fan", "风扇", "fæn", 2},
    {"wall", "墙壁", "wɔːl", 2},
    {"floor", "地板", "flɔː", 2},
    {"really", "真的", "'rɪəlɪ", 2},
    {"near", "距离近", "nɪə", 2},
    {"TV", "电视", "ˌti: ˈvi:", 2},
    {"clean", "打扫", "kliːn", 2},
    {"help", "帮助", "help", 2},
    {"schoolbag", "书包", "'skuːlbæɡ", 2},
    {"maths book", "数学书", "", 2},
    {"English book", "英语书", "", 2},
    {"Chinese book", "语文书", "", 2},
    {"storybook", "故事书", "'stɔːrɪbʊk", 2},
    {"candy", "糖果", "'kændɪ", 2},
    {"notebook", "笔记本", "'nəʊtbʊk", 2},
    {"key", "钥匙", "kiː", 2},
    {"wow", "呀", "waʊ", 2},
    {"lost", "丢失", "lɒst", 2},
    {"so much", "非常地", "", 2},
    {"cute", "可爱的", "kjuːt", 2},
    {"strong", "强壮的", "strɒŋ", 2},
    {"friendly", "友好的", "ˈfrendlɪ", 2},
    {"quiet", "安静的", "'kwaɪət", 2},
    {"hair", "头发", "heə", 2},
    {"shoe", "鞋", "ʃuː", 2},
    {"glasses", "眼镜", "'glɑːsɪz", 2},
    {"his", "他的", "hɪz", 2},
    {"or", "或者", "ɔː", 2},
    {"right", "对的", "raɪt", 2},
    {"hat", "帽子", "hæt", 2},
    {"her", "她的", "hɜː", 2},
    {"bedroom", "卧室", "'bedruːm; -rʊm", 2},
    {"living room", "客厅", "'lɪvɪŋ ru:m", 2},
    {"study", "书房", "'stʌdɪ", 2},
    {"kitchen", "厨房", "'kɪtʃɪn; -tʃ(ə)n", 2},
    {"bathroom", "浴室", "'bɑːθruːm; -rʊm", 2},
    {"bed", "床", "bed", 2},
    {"phone", "电话", "fəʊn", 2},
    {"table", "桌子", "'teɪb(ə)l", 2},
    {"sofa", "长沙发", "'səʊfə", 2},
    {"fridge", "冰箱", "frɪdʒ", 2},
    {"find", "找到", "faɪnd", 2},
    {"them", "他们", "ðem; ðəm", 2},
    {"beef", "牛肉", "biːf", 2},
    {"chicken", "鸡肉", "'tʃɪkɪn", 2},
    {"noodles", "面条", "ˈnu:dlz", 2},
    {"soup", "汤", "suːp", 2},
    {"vegetable", "蔬菜", "ˈvedʒtəbl", 2},
    {"chopsticks", "筷子", "'tʃɒpstɪks", 2},
    {"bowl", "碗", "bəʊl", 2},
    {"fork", "餐叉", "fɔːk", 2},
    {"knife", "刀", "naɪf", 2},
    {"spoon", "匙", "spuːn", 2},
    {"dinner", "正餐", "'dɪnə", 2},
    {"ready", "准备好", "'redɪ", 2},
    {"help yourself", "为取用", "", 2},
    {"pass", "给", "pɑːs", 2},
    {"try", "试", "traɪ", 2},
    {"parents", "父母", "'peərənts", 2},
    {"cousin", "同辈表亲", "'kʌz(ə)n", 2},
    {"uncle", "叔叔", "'ʌŋk(ə)l", 2},
    {"aunt", "阿姨", "ɑːnt", 2},
    {"baby brother", "小弟弟", "", 2},
    {"doctor", "医生", "'dɒktə", 2},
    {"cook", "厨师", "kʊk", 2},
    {"driver", "司机", "'draɪvə", 2},
    {"farmer", "农民", "'fɑːmə", 2},
    {"nurse", "护士", "nɜːs", 2},
    {"people", "人们", "'piːp(ə)l", 2},
    {"but", "但是", "bʌt; bət", 2},
    {"little", "小的", "'lɪt(ə)l", 2},
    {"puppy", "小狗", "'pʌpɪ", 2},
    {"football player", "足球运动员", "", 2},
    {"job", "工作", "dʒɒb", 2},
    {"basketball", "篮球", "'bɑːskɪtbɔːl", 2},
    {"first floor", "一楼", "", 3},
    {"second floor", "二楼", "", 3},
    {"teacher's office", "教师办公室", "", 3},
    {"library", "图书馆", "ˈlaɪbrərɪ", 3},
    {"playground", "操场", "'pleɪgraʊnd", 3},
    {"computer room", "计算机房", "", 3},
    {"art room", "美术教室", "", 3},
    {"music room", "音乐教室", "", 3},
    {"next to", "紧邻", "", 3},
    {"homework", "作业", "'həʊmwɜːk", 3},
    {"class", "班级", "klɑːs", 3},
    {"forty", "四十", "'fɔːtɪ", 3},
    {"way", "方向", "weɪ", 3},
    {"breakfast", "早餐", "'brekfəst", 3},
    {"English class", "英语课", "", 3},
    {"lunch", "午饭", "lʌn(t)ʃ", 3},
    {"music class", "音乐课", "", 3},
    {"PE class", "体育课", "", 3},
    {"get up", "起床", "", 3},
    {"go to school", "上学", "", 3},
    {"go home", "回家", "", 3},
    {"go to bed", "去睡觉", "", 3},
    {"over", "结束", "'əʊvə", 3},
    {"now", "现在", "naʊ", 3},
    {"o'clock", "⋯⋯点钟", "ə'klɒk", 3},
    {"kid", "小孩", "kɪd", 3},
    {"thirty", "三十", "'θɜːtɪ", 3},
    {"hurry up", "快点", "'hʌrɪ ʌp", 3},
    {"come on", "加油", "", 3},
    {"just a minute", "稍等一会儿", "", 3},
    {"cold", "冷的", "kəʊld", 3},
    {"cool", "凉的", "kuːl", 3},
    {"warm", "温暖的", "wɔːm", 3},
    {"hot", "热的", "hɒt", 3},
    {"sunny", "阳光充足的", "'sʌnɪ", 3},
    {"windy", "多风的", "'wɪndɪ", 3},
    {"cloudy", "多云的", "'klaʊdɪ", 3},
    {"snowy", "下雪的", "'snəʊɪ", 3},
    {"rainy", "阴雨的", "'reɪnɪ", 3},
    {"outside", "在户外", "aʊt'saɪd; 'aʊtsaɪd", 3},
    {"be careful", "小心", "", 3},
    {"weather", "天气", "'weðə", 3},
    {"New York", "纽约", "", 3},
    {"how about...", "怎么样？", "", 3},
    {"degree", "度", "dɪ'griː", 3},
    {"world", "世界", "wɜːld", 3},
    {"London", "伦敦", "ˈlʌndən", 3},
    {"Moscow", "莫斯科", "'mɔskəʊ", 3},
    {"Singapore", "新加坡城", "ˌsɪŋgə'pɔ:", 3},
    {"Sydney", "悉尼", "ˈsɪdnɪ", 3},
    {"fly", "放", "flaɪ", 3},
    {"love", "爱你的", "lʌv", 3},
    {"tomato", "西红柿", "tə'mɑːtəʊ", 3},
    {"potato", "马铃薯", "pə'teɪtəʊ", 3},
    {"green beans", "豆角", "", 3},
    {"carrot", "胡萝卜", "'kærət", 3},
    {"horse", "马", "hɔːs", 3},
    {"cow", "牛", "kaʊ", 3},
    {"sheep", "绵羊", "ʃiːp", 3},
    {"hen", "母鸡", "hen", 3},
    {"these", "这些", "ðiːz", 3},
    {"yum", "味道好", "jʌm", 3},
    {"animal", "动物", "'ænɪm(ə)l", 3},
    {"those", "那些", "ðəʊz", 3},
    {"garden", "花园", "'gɑːd(ə)n", 3},
    {"farm", "农场", "fɑːm", 3},
    {"goat", "山羊", "gəʊt", 3},
    {"eat", "吃", "iːt", 3},
    {"clothes", "服装", "kləʊ(ð)z", 3},
    {"pants", "裤子", "pæn(t)s", 3},
    {"dress", "连衣裙", "dres", 3},
    {"skirt", "女裙", "skɜːt", 3},
    {"coat", "大衣", "kəʊt", 3},
    {"sweater", "毛衣", "'swetə", 3},
    {"sock", "短袜", "sɒk", 3},
    {"shorts", "短裤", "ʃɔːts", 3},
    {"jacket", "夹克衫", "'dʒækɪt", 3},
    {"shirt", "衬衫", "ʃɜːt", 3},
    {"yours", "你的", "jɔːz; jʊəz", 3},
    {"whose", "谁的", "huːz", 3},
    {"mine", "我的", "maɪn", 3},
    {"pack", "收拾", "pæk", 3},
    {"wait", "等待", "weɪt", 3},
    {"glove", "手套", "glʌv", 3},
    {"scarf", "围巾", "skɑːf", 3},
    {"umbrella", "伞", "ʌm'brelə", 3},
    {"sunglasses", "太阳镜", "'sʌnglɑːsɪz", 3},
    {"pretty", "美丽的", "'prɪtɪ", 3},
    {"expensive", "贵的", "ɪkˈspensɪv", 3},
    {"cheap", "便宜的", "tʃiːp", 3},
    {"nice", "好的", "naɪs", 3},
    {"try on", "试穿", "", 3},
    {"size", "尺码", "saɪz", 3},
    {"of course", "当然", "", 3},
    {"too", "太", "tuː", 3},
    {"just", "正好", "dʒʌst", 3},
    {"how much", "多少钱", "haʊ mʌtʃ", 3},
    {"eighty", "八十", "'eɪtɪ", 3},
    {"dollar", "元", "'dɒlə", 3},
    {"sale", "特价销售", "seɪl", 3},
    {"more", "更多的", "mɔː", 3},
    {"us", "我们", "əs; ʌs", 3},
    {"old", "老的", "əʊld", 4},
    {"young", "年轻的", "jʌŋ", 4},
    {"kind", "体贴的", "kaɪnd", 4},
    {"strict", "严厉的", "strɪkt", 4},
    {"polite", "有礼貌的", "pə'laɪt", 4},
    {"hard-working", "努力的", "ˈhɑːdˈwɜːkɪŋ", 4},
    {"helpful", "有用的", "'helpfʊl; -f(ə)l", 4},
    {"clever", "聪明的", "'klevə", 4},
    {"shy", "羞怯的", "ʃaɪ", 4},
    {"know", "知道", "nəʊ", 4},
    {"our", "我们的", "aʊə", 4},
    {"Ms", "女士", "", 4},
    {"will", "将要", "wɪl", 4},
    {"sometimes", "有时", "'sʌmtaɪmz", 4},
    {"robot", "机器人", "'rəʊbɒt", 4},
    {"him", "他", "hɪm", 4},
    {"speak", "会说", "spiːk", 4},
    {"finish", "完成", "'fɪnɪʃ", 4},
    {"Monday", "星期一", "ˈmʌndeɪ; ˈmʌndi", 4},
    {"Tuesday", "星期二", "'tjuːzdeɪ; -dɪ", 4},
    {"Wednesday", "星期三", "ˈwenzdɪ", 4},
    {"Thursday", "星期四", "'θɜːzdeɪ; -dɪ", 4},
    {"Friday", "星期五", "ˈfraɪdeɪ", 4},
    {"Saturday", "星期六", "ˈsætədɪ; -deɪ", 4},
    {"Sunday", "星期日", "ˈsʌndeɪ; ˈsʌndi", 4},
    {"weekend", "周末", "wiːkˈɛnd", 4},
    {"wash", "洗", "wɒʃ", 4},
    {"wash my clothes", "洗我的衣服", "", 4},
    {"watch", "看", "wɒtʃ", 4},
    {"watch TV", "看电视", "", 4},
    {"do", "做", "duː", 4},
    {"do homework", "做作业", "", 4},
    {"read", "看", "ri:d;red", 4},
    {"read books", "看书", "", 4},
    {"play", "玩", "pleɪ", 4},
    {"play football", "踢足球", "", 4},
    {"cooking", "烹饪", "'kʊkɪŋ", 4},
    {"often", "时常", "'ɒf(tə)n", 4},
    {"park", "公园", "pɑːk", 4},
    {"tired", "疲倦的", "taɪəd", 4},
    {"sport", "体育运动", "spɔːt", 4},
    {"play sports", "做体育运动", "", 4},
    {"should", "应该", "ʃəd; strong form ʃʊd", 4},
    {"every", "每一个", "'evrɪ", 4},
    {"day", "一天", "deɪ", 4},
    {"schedule", "工作计划", "ˈʃedju:l", 4},
    {"sandwich", "三明治", "'sæn(d)wɪdʒ; -wɪtʃ", 4},
    {"salad", "沙拉", "'sæləd", 4},
    {"hamburger", "汉堡包", "ˈhæmbɜ:gə", 4},
    {"ice cream", "冰淇淋", "aɪs kri:m", 4},
    {"tea", "茶", "tiː", 4},
    {"fresh", "新鲜的", "freʃ", 4},
    {"healthy", "健康的", "'helθɪ", 4},
    {"delicious", "美味的", "dɪ'lɪʃəs", 4},
    {"sweet", "甜的", "swiːt", 4},
    {"drink", "喝", "drɪŋk", 4},
    {"thirsty", "渴的", "'θɜːstɪ", 4},
    {"favourite", "特别喜欢的", "'feɪv(ə)rɪt", 4},
    {"food", "食物", "fuːd", 4},
    {"Dear", "亲爱的", "dɪə", 4},
    {"onion", "洋葱", "'ʌnjən", 4},
    {"sing", "唱", "sɪŋ", 4},
    {"song", "歌曲", "sɒŋ", 4},
    {"sing English songs", "唱英文歌曲", "", 4},
    {"play the pipa", "弹琵琶", "", 4},
    {"kung fu", "功夫", ",kʌŋ'fu:", 4},
    {"do kung fu", "练武术", "", 4},
    {"dance", "跳舞", "dɑːns", 4},
    {"draw", "画", "drɔː", 4},
    {"cartoon", "漫画", "kɑː'tuːn", 4},
    {"draw cartoons", "画漫画", "", 4},
    {"swim", "游泳", "swɪm", 4},
    {"play basketball", "打篮球", "", 4},
    {"ping-pong", "乒乓球", "", 4},
    {"play ping-pong", "打乒乓球", "", 4},
    {"speak English", "说英语", "", 4},
    {"we'll", "我们将……", "wel", 4},
    {"party", "聚会", "'pɑːtɪ", 4},
    {"next", "下一个的", "nekst", 4},
    {"wonderful", "极好的", "ˈwʌndə(r)fl", 4},
    {"learn", "学习", "lɜːn", 4},
    {"any", "任何的", "'enɪ", 4},
    {"problem", "没问题", "'prɒbləm", 4},
    {"no problem", "没问题", "", 4},
    {"want", "要", "wɒnt", 4},
    {"send", "邮寄", "send", 4},
    {"email", "电子邮件", "'iːmeɪl", 4},
    {"clock", "时钟", "klɒk", 4},
    {"plant", "植物", "plɑːnt", 4},
    {"bottle", "瓶子", "'bɒt(ə)l", 4},
    {"water bottle", "水瓶", "", 4},
    {"bike", "自行车", "baɪk", 4},
    {"photo", "照片", "'fəʊtəʊ", 4},
    {"front", "正面", "frʌnt", 4},
    {"in front of", "在⋯⋯前面", "ɪn frʌnt əv", 4},
    {"between", "在⋯⋯中间", "bɪ'twiːn", 4},
    {"above", "在⋯⋯上面", "ə'bʌv", 4},
    {"beside", "在旁边", "bɪ'saɪd", 4},
    {"behind", "在⋯⋯后面", "bɪ'haɪnd", 4},
    {"grandparent", "祖父母", "'græn(d)peər(ə)nt", 4},
    {"their", "他们的", "ðeə", 4},
    {"house", "房子", "haʊs", 4},
    {"lot", "大量", "lɒt", 4},
    {"lots of", "大量", "", 4},
    {"flower", "花", "'flaʊə", 4},
    {"move", "搬家", "muːv", 4},
    {"dirty", "肮脏的", "'dɜːtɪ", 4},
    {"everywhere", "处处", "'evrɪweə", 4},
    {"mouse", "老鼠", "maʊs", 4},
    {"live", "住", "laɪv；lɪv", 4},
    {"nature", "自然界", "'neɪtʃə", 4},
    {"forest", "森林", "'fɒrɪst", 4},
    {"river", "河", "'rɪvə", 4},
    {"lake", "湖", "leɪk", 4},
    {"mountain", "山", "ˈmaʊntən", 4},
    {"hill", "小山", "hɪl", 4},
    {"tree", "树", "triː", 4},
    {"bridge", "桥", "brɪdʒ", 4},
    {"building", "建筑", "'bɪldɪŋ", 4},
    {"village", "村庄", "'vɪlɪdʒ", 4},
    {"house.", "房屋", "haʊs", 4},
    {"boating", "划船", "'bəʊtɪŋ", 4},
    {"go boating", "去划船", "", 4},
    {"aren't", "不是", "ɑ:nt", 4},
    {"rabbit", "兔", "'ræbɪt", 4},
    {"high", "高的", "haɪ", 4},
    {"eat breakfast", "吃早饭", "it brɛkfəst", 5},
    {"have...class", "上⋯⋯课", "", 5},
    {"exercise", "活动", "'eksəsaɪz", 5},
    {"do morning exercise", "做早操", "", 5},
    {"eat dinner", "吃晚饭", "", 5},
    {"clean my room", "打扫我的房间", "", 5},
    {"go for a walk", "散步", "", 5},
    {"go shopping", "购物", "", 5},
    {"take", "上", "teɪk", 5},
    {"dancing", "跳舞", "'dɑːnsɪŋ", 5},
    {"take a dancing class", "上舞蹈课", "", 5},
    {"when", "什么时候", "wen", 5},
    {"after", "在⋯⋯之后", "'ɑːftə", 5},
    {"start", "开始", "stɑːt", 5},
    {"usually", "通常地", "ˈjuːʒʊəlɪ", 5},
    {"Spain", "西班牙", "spein", 5},
    {"late", "晚", "leɪt", 5},
    {"a.m.", "上午", "", 5},
    {"p.m.", "下午", "", 5},
    {"why", "为什么", "waɪ", 5},
    {"shop", "购物", "ʃɒp", 5},
    {"work", "工作", "wɜːk", 5},
    {"last", "上一个的", "lɑːst", 5},
    {"sound", "听起来好像", "saʊnd", 5},
    {"also", "还", "'ɔːlsəʊ", 5},
    {"busy", "忙的", "'bɪzɪ", 5},
    {"need", "需要", "niːd", 5},
    {"letter", "信", "'letə", 5},
    {"island", "岛", "'aɪlənd", 5},
    {"always", "总是", "ˈɔ:lweɪz", 5},
    {"cave", "山洞", "keɪv", 5},
    {"go swimming", "去游泳", "", 5},
    {"win", "获胜", "wɪn", 5},
    {"spring", "春天", "sprɪŋ", 5},
    {"summer", "夏天", "'sʌmə", 5},
    {"autumn", "秋天", "'ɔːtəm", 5},
    {"winter", "冬天", "'wɪntə", 5},
    {"season", "季节", "'siːz(ə)n", 5},
    {"picnic", "野餐", "'pɪknɪk", 5},
    {"go on a picnic", "去野餐", "", 5},
    {"pick", "摘", "pɪk", 5},
    {"pick apples", "摘苹果", "", 5},
    {"snowman", "雪人", "'snəʊmæn", 5},
    {"make a snowman", "堆雪人", "", 5},
    {"go swimming.", "去游泳", "", 5},
    {"which", "哪一个", "wɪtʃ", 5},
    {"best", "最", "best", 5},
    {"snow", "雪", "snəʊ", 5},
    {"good job", "做得好", "", 5},
    {"because", "因为", "bɪ'kɒz", 5},
    {"vacation", "假期", "vəˈkeɪʃn", 5},
    {"all", "完全", "ɔːl", 5},
    {"pink", "粉色", "pɪŋk", 5},
    {"lovely", "可爱的", "'lʌvlɪ", 5},
    {"leaf", "叶子", "liːf", 5},
    {"fall", "落下", "fɔːl", 5},
    {"paint", "绘画", "peɪnt", 5},
    {"January", "一月", "'dʒænjʊ(ə)rɪ", 5},
    {"February", "二月", "ˈfebrʊərɪ", 5},
    {"March", "三月", "mɑːtʃ", 5},
    {"April", "四月", "'eɪprəl", 5},
    {"May", "五月", "meɪ", 5},
    {"June", "六月", "dʒu:n", 5},
    {"July", "七月", "dʒʊˈlaɪ", 5},
    {"August", "八月", "ɔ:ˈgʌst", 5},
    {"September", "九月", "sep'tembə", 5},
    {"October", "十月", "ɒk'təʊbə", 5},
    {"November", "十一月", "nə(ʊ)'vembə", 5},
    {"December", "十二月", "dɪ'sembə", 5},
    {"few", "不多", "fjuː", 5},
    {"a few", "一些", "", 5},
    {"thing", "事情", "θɪŋ", 5},
    {"meet", "集会", "miːt", 5},
    {"sports meet", "运动会", "", 5},
    {"Easter", "复活节", "'i:stə", 5},
    {"trip", "旅行", "trɪp", 5},
    {"year", "年", "jɪə; jɜː", 5},
    {"contest", "比赛", "'kɒntest", 5},
    {"the Great Wall", "长城", "", 5},
    {"national", "国家的", "'næʃ(ə)n(ə)l", 5},
    {"National Day", "国庆日", "ˈnæʃənəl de", 5},
    {"American", "美国的", "əˈmerɪkən", 5},
    {"Thanksgiving", "感恩节", "", 5},
    {"Christmas", "圣诞节", "ˈkrɪsməs", 5},
    {"holiday", "节日", "'hɒlɪdeɪ; -dɪ", 5},
    {"game", "游戏", "geɪm", 5},
    {"roll", "滚动", "rəʊl", 5},
    {"look for", "寻找", "", 5},
    {"chocolate", "巧克力", "'tʃɒk(ə)lət", 5},
    {"bunny", "兔子", "'bʌnɪ", 5},
    {"RSVP", "请赐复", "", 5},
    {"by", "在⋯⋯之前", "baɪ", 5},
    {"first", "第一", "fɜːst", 5},
    {"second", "第二", "'sek(ə)nd", 5},
    {"third", "第三", "θɜːd", 5},
    {"fourth", "第四", "fɔːθ", 5},
    {"fifth", "第五", "fɪfθ", 5},
    {"twelfth", "第十二", "twelfθ", 5},
    {"twentieth", "第二十", "ˈtwentɪəθ", 5},
    {"twenty-first", "第二十一", "'twenti'fə:st", 5},
    {"twenty-third", "第二十三", "", 5},
    {"thirtieth", "第三十", "'θɜːtɪɪθ", 5},
    {"special", "特殊的", "'speʃ(ə)l", 5},
    {"fool", "蠢人", "fuːl", 5},
    {"kitten", "小猫", "'kɪt(ə)n", 5},
    {"diary", "日记", "'daɪərɪ", 5},
    {"still", "仍然", "stɪl", 5},
    {"noise", "噪音", "nɔɪz", 5},
    {"fur", "动物皮毛", "fɜː", 5},
    {"open", "开着的", "'əʊp(ə)n", 5},
    {"walk", "行走", "wɔːk", 5},
    {"hers", "她的", "hɜːz", 5},
    {"theirs", "他们的", "ðeəz", 5},
    {"ours", "我们的", "aʊəz", 5},
    {"climbing", "攀登", "'klaɪmɪŋ", 5},
    {"eating", "吃", "'iːtɪŋ", 5},
    {"playing", "玩", "'pleɪŋ", 5},
    {"jumping", "跳", "'dʒʌmpɪŋ", 5},
    {"drinking", "喝", "'drɪŋkɪŋ", 5},
    {"sleeping", "睡觉", "'sliːpɪŋ", 5},
    {"each", "每个", "iːtʃ", 5},
    {"other", "其他", "'ʌðə", 5},
    {"each other", "相互", "", 5},
    {"excited", "兴奋地", "ɪk'saɪtɪd", 5},
    {"like", "像⋯⋯那样", "laɪk", 5},
    {"doing morning exercises", "做早操", "", 5},
    {"having...class", "上⋯⋯课", "", 5},
    {"eating lunch", "吃午饭", "", 5},
    {"reading a book", "看书", "", 5},
    {"listening to music", "听音乐", "", 5},
    {"keep", "保持", "kiːp", 5},
    {"keep to the right", "靠右", "", 5},
    {"keep your desk clean", "保持课桌干净", "", 5},
    {"talk quietly", "小声讲话", "", 5},
    {"turn", "顺序", "tɜːn", 5},
    {"take turns", "按顺序来", "", 5},
    {"bamboo", "竹子", "bæm'buː", 5},
    {"its", "它的", "ɪts", 5},
    {"show", "指导", "ʃəʊ", 5},
    {"anything", "任何事物", "'enɪθɪŋ", 5},
    {"else", "另外", "els", 5},
    {"exhibition", "展览", "ˌeksɪˈbɪʃn", 5},
    {"say", "说", "seɪ", 5},
    {"have a look", "看一看", "", 5},
    {"sushi", "寿司", "'suːʃɪ", 5},
    {"teach", "教", "tiːtʃ", 5},
    {"sure", "当然", "ʃɔ:(r)", 5},
    {"Canadian", "加拿大的", "kə'neɪdɪən", 5},
    {"Spanish", "西班牙的", "'spænɪʃ", 5},
    {"science", "科学", "'saɪəns", 6},
    {"museum", "博物馆", "mjuː'zɪəm", 6},
    {"post office", "邮局", "ˈpəust ɔfis", 6},
    {"bookstore", "书店", "'bʊkstɔː", 6},
    {"cinema", "电影院", "ˈsɪnəmɑ:ˈsɪnəmə", 6},
    {"hospital", "医院", "'hɒspɪt(ə)l", 6},
    {"crossing", "十字路口", "'krɒsɪŋ", 6},
    {"left", "左", "left", 6},
    {"on foot", "步行", "", 6},
    {"bus", "公共汽车", "bʌs", 6},
    {"plane", "飞机", "pleɪn", 6},
    {"taxi", "出租汽车", "'tæksɪ", 6},
    {"ship", "船", "ʃɪp", 6},
    {"subway", "地铁", "'sʌbweɪ", 6},
    {"train", "火车", "treɪn", 6},
    {"slow", "慢的", "sləʊ", 6},
    {"down", "减少", "daʊn", 6},
    {"slow down", "慢下来", "", 6},
    {"stop", "停下", "stɒp", 6},
    {"Mrs", "夫人", "ˈmɪsɪz", 6},
    {"early", "早到的", "'ɜːlɪ", 6},
    {"helmet", "头盔", "'helmɪt", 6},
    {"must", "必须", "mʌst", 6},
    {"wear", "戴", "weə", 6},
    {"attention", "注意", "ə'tenʃ(ə)n", 6},
    {"pay attention to", "注意", "", 6},
    {"traffic", "交通", "'træfɪk", 6},
    {"traffic lights", "交通信号灯", "", 6},
    {"Munich", "慕尼黑", "'mju:nik", 6},
    {"Germany", "德国", "'dʒɜːmənɪ", 6},
    {"Alaska", "阿拉斯加州", "ə'læskə", 6},
    {"sled", "雪橇", "sled", 6},
    {"fast", "快的", "fɑːst", 6},
    {"ferry", "轮渡", "'ferɪ", 6},
    {"Papa Westray", "帕帕韦斯特雷岛", "", 6},
    {"Scotland", "苏格兰", "'skɔtlənd", 6},
    {"visit", "拜访", "'vɪzɪt", 6},
    {"film", "电影", "fɪlm", 6},
    {"see a film", "看电影", "", 6},
    {"take a trip", "去旅行", "", 6},
    {"supermarket", "超市", "'suːpəmɑːkɪt; 'sjuː-", 6},
    {"evening", "晚上", "'iːv(ə)nɪŋ", 6},
    {"tonight", "今晚", "tə'naɪt", 6},
    {"tomorrow", "明天", "tə'mɒrəʊ", 6},
    {"next week", "下周", "nekst wi:k", 6},
    {"dictionary", "词典", "'dɪkʃ(ə)n(ə)rɪ", 6},
    {"comic", "滑稽的", "'kɒmɪk", 6},
    {"comic book", "连环画", "", 6},
    {"word", "单词", "wɜːd", 6},
    {"word book", "单词书", "'wɜːdbʊk", 6},
    {"post card", "明信片", "", 6},
    {"lesson", "课", "'les(ə)n", 6},
    {"space", "太空", "speɪs", 6},
    {"travel", "旅行", "'træv(ə)l", 6},
    {"half", "一半", "hɑːf", 6},
    {"price", "价格", "praɪs", 6},
    {"Mid-Autumn Festival", "中秋节", "", 6},
    {"together", "一起", "tə'geðə", 6},
    {"get together", "聚会", "", 6},
    {"mooncake", "月饼", "'mu:nkeɪk", 6},
    {"poem", "诗", "'pəʊɪm", 6},
    {"moon", "月亮", "muːn", 6},
    {"studies", "学习", "'stʌdiz", 6},
    {"puzzle", "谜", "'pʌz(ə)l", 6},
    {"hiking", "远足", "'haɪkɪŋ", 6},
    {"pen pal", "笔友", "", 6},
    {"hobby", "业余爱好", "'hɒbɪ", 6},
    {"jasmine", "茉莉", "'dʒæzmɪn; 'dʒæs-", 6},
    {"idea", "主意", "aɪ'dɪə", 6},
    {"Canberra", "堪培拉", "'kænbərə", 6},
    {"amazing", "令人惊奇的", "ə'meɪzɪŋ", 6},
    {"shall", "表示征求意见", "ʃæl; ʃ(ə)l", 6},
    {"goal", "射门", "gəʊl", 6},
    {"join", "加入", "dʒɒɪn", 6},
    {"club", "俱乐部", "klʌb", 6},
    {"share", "分享", "ʃeə", 6},
    {"factory", "工厂", "'fækt(ə)rɪ", 6},
    {"worker", "工人", "'wɜːkə", 6},
    {"postman", "邮递员", "'pəʊs(t)mən", 6},
    {"businessman", "商人", "'bɪznɪsmən", 6},
    {"police officer", "警察", "pəˈlis ˈɔfɪsɚ", 6},
    {"fisherman", "渔民", "'fɪʃəmən", 6},
    {"scientist", "科学家", "'saɪəntɪst", 6},
    {"pilot", "飞行员", "'paɪlət", 6},
    {"coach", "教练", "kəʊtʃ", 6},
    {"country", "国家", "'kʌntrɪ", 6},
    {"head teacher", "校长", "", 6},
    {"sea", "大海", "siː", 6},
    {"stay", "保持", "steɪ", 6},
    {"university", "大学", "juːnɪ'vɜːsɪtɪ", 6},
    {"gym", "体育馆", "dʒɪm", 6},
    {"if", "如果", "ɪf", 6},
    {"reporter", "记者", "rɪ'pɔːtə", 6},
    {"use", "使用", "juːz", 6},
    {"type", "打字", "taɪp", 6},
    {"quickly", "迅速地", "'kwɪklɪ", 6},
    {"secretary", "秘书", "ˈsekrətrɪ", 6},
    {"angry", "生气的", "'æŋgrɪ", 6},
    {"afraid", "害怕", "ə'freɪd", 6},
    {"sad", "难过的", "sæd", 6},
    {"worried", "担心的", "'wʌrɪd", 6},
    {"happy", "高兴的", "'hæpɪ", 6},
    {"see a doctor", "看病", "", 6},
    {"wear.", "穿", "weə", 6},
    {"deep", "深的", "diːp", 6},
    {"breath", "呼吸", "breθ", 6},
    {"take a deep breath", "深呼吸", "", 6},
    {"count", "数数", "kaʊnt", 6},
    {"count to ten", "数到十", "", 6},
    {"chase", "追赶", "tʃeɪs", 6},
    {"mice", "老鼠", "maɪs", 6},
    {"bad", "邪恶的", "bæd", 6},
    {"hurt", "受伤", "hɜːt", 6},
    {"ill", "有病", "ɪl", 6},
    {"wrong", "有毛病", "rɒŋ", 6},
    {"feel", "觉得", "fiːl", 6},
    {"well", "健康", "wel", 6},
    {"sit", "坐", "sɪt", 6},
    {"grass", "草坪", "grɑːs", 6},
    {"ant", "蚂蚁", "ænt", 6},
    {"worry", "担心", "'wʌrɪ", 6},
    {"stuck", "陷住", "stʌk", 6},
    {"mud", "泥", "mʌd", 6},
    {"pull", "拉", "pʊl", 6},
    {"everyone", "每人", "'evrɪwʌn", 6},
    {"younger", "更年轻的", "'jʌŋɡə", 7},
    {"older", "更年长的", "'əʊldə", 7},
    {"taller", "更高的", "'tɔ:lə(r)", 7},
    {"shorter", "更矮的", "", 7},
    {"longer", "更长的", "'lɒŋɡə", 7},
    {"thinner", "更瘦的", "'θɪnə", 7},
    {"heavier", "更重的", "'hevɪə", 7},
    {"bigger", "更大的", "bɪgə(r)", 7},
    {"smaller", "更小的", "smɔ:lə(r)", 7},
    {"stronger", "更强壮的", "strɒŋgə(r)", 7},
    {"dinosaur", "恐龙", "'daɪnəsɔː", 7},
    {"hall", "大厅", "hɔːl", 7},
    {"metre", "米", "'mi:tə(r)", 7},
    {"meter", "米", "ˈmi:tə(r)", 7},
    {"than", "比", "ðæn; ð(ə)n", 7},
    {"both", "两个都", "bəʊθ", 7},
    {"kilogram", "千克", "ˈkɪləɡræm", 7},
    {"countryside", "乡村", "'kʌntrɪsaɪd", 7},
    {"lower", "更低地", "'ləʊə", 7},
    {"shadow", "影子", "'ʃædəʊ", 7},
    {"smarter", "更聪明的", "'smɑ:tə", 7},
    {"become", "变成", "bɪ'kʌm", 7},
    {"cleaned", "打扫", "kliːnd", 7},
    {"stayed", "待", "", 7},
    {"washed", "洗", "wɔʃt", 7},
    {"watched", "看", "wɒtʃ", 7},
    {"had", "得病", "hæd", 7},
    {"had a cold", "感冒", "", 7},
    {"slept", "睡觉", "slept", 7},
    {"saw", "看", "sɔː", 7},
    {"yesterday", "昨天", "ˈjestədɪ;-deɪ", 7},
    {"before", "在⋯⋯之前", "bɪ'fɔː", 7},
    {"drank", "喝", "dræŋk", 7},
    {"magazine", "杂志", "mægə'ziːn", 7},
    {"better", "更好的", "'betə", 7},
    {"faster", "更快的", "fɑ:stə(r)", 7},
    {"hotel", "旅馆", "həʊˈtel", 7},
    {"fixed", "修理", "fɪkst", 7},
    {"broken", "破损的", "'brəʊk(ə)n", 7},
    {"lamp", "台灯", "læmp", 7},
    {"loud", "大声的", "laʊd", 7},
    {"enjoy", "享受⋯⋯的乐趣", "ɪnˈdʒɔɪ", 7},
    {"went", "去", "went", 7},
    {"camp", "野营", "kæmp", 7},
    {"went camping", "去野营", "", 7},
    {"went fishing", "去钓鱼", "", 7},
    {"rode", "骑", "rəʊd", 7},
    {"ate", "吃", "et; eit", 7},
    {"took", "拍照", "tʊk", 7},
    {"took pictures", "照相", "", 7},
    {"bought", "买", "bɔːt", 7},
    {"gift", "礼物", "gɪft", 7},
    {"fell", "摔倒", "fel", 7},
    {"off", "落下", "ɒf", 7},
    {"Labour Day", "劳动节", "", 7},
    {"mule", "骡子", "mjuːl", 7},
    {"Turpan", "吐鲁番", "", 7},
    {"could", "能", "kəd; kʊd", 7},
    {"till", "直到", "tɪl", 7},
    {"beach", "沙滩", "biːtʃ", 7},
    {"basket", "篮子", "'bɑːskɪt", 7},
    {"part", "角色", "pɑːt", 7},
    {"licked", "舔", "lɪk", 7},
    {"laughed", "笑", "", 7},
    {"dining hall", "饭厅", "", 7},
    {"ago", "以前", "ə'gəʊ", 7},
    {"cycling", "骑自行车运动", "'saɪklɪŋ", 7},
    {"go cycling", "去骑自行车", "", 7},
    {"ice-skate", "滑冰", "'aisskeit", 7},
    {"badminton", "羽毛球运动", "'bædmɪnt(ə)n", 7},
    {"star", "星", "stɑː", 7},
    {"easy", "容易的", "'iːzɪ", 7},
    {"look up", "查阅", "", 7},
    {"Internet", "互联网", "'ɪntənet", 7},
    {"different", "不同的", "ˈdɪfrənt", 7},
    {"active", "活跃的", "'æktɪv", 7},
    {"race", "赛跑", "reɪs", 7},
    {"nothing", "没有什么", "'nʌθɪŋ", 7},
    {"thought", "想", "θɔːt", 7},
    {"felt", "感觉", "felt", 7},
    {"cheetah", "猎豹", "'tʃiːtə", 7},
    {"woke", "醒", "wəʊk", 7},
    {"dream", "梦", "driːm", 7},
    {"straight", "笔直的", "streɪt", 7},
    {"ask", "问", "ɑːsk", 7},
    {"sir", "先生", "sɜː", 7},
    {"interesting", "有趣的", "ˈɪntrəstɪŋ", 7},
    {"Italian", "意大利的", "ɪˈtælɪən", 7},
    {"restaurant", "餐馆", "ˈrestrɒnt", 7},
    {"pizza", "比萨饼", "'piːtsə; 'pɪtsə", 7},
    {"street", "大街", "striːt", 7},
    {"get", "到达", "get", 7},
    {"GPS", "全球", "", 7},
    {"gave", "提供", "ɡeɪv", 7},
    {"feature", "特点", "'fiːtʃə", 7},
    {"follow", "跟着", "'fɒləʊ", 7},
    {"far", "较远的", "fɑː", 7},
    {"tell", "告诉", "tel", 7},
};

#endif